import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import { meadowEntryArtPackageApproval } from '$lib/game/content/approvals/meadow-entry-art-package';
import { MEADOW_ENTRY_BAKE_OWNERSHIP } from '$lib/game/content/backgrounds/meadow-entry-bake-ownership';
import { MEADOW_ENTRY_APPROVED_CROPS } from '$lib/game/content/backgrounds/meadow-entry-crop-manifest';
import { SUNDROP_VILLAGE_OBSTACLE_OWNERSHIP } from '$lib/game/content/backgrounds/sundrop-village-obstacle-ownership';

import {
	collectMeadowEntryRuntimeData,
	renderMeadowEntryRuntimeData,
	syncGeneratedMeadowEntryRuntimeData
} from '../../../../../tools/generate-meadow-entry-runtime';

const RUNTIME_REQUIREMENTS = new Set([
	'existing-blocker-fallback',
	'extend-decor-fallback',
	'extend-fence-fallback'
]);
const SUNDROP_BLOCKER_IDS = new Set(
	SUNDROP_VILLAGE_OBSTACLE_OWNERSHIP.map(({ blockerId }) => blockerId)
);
const temporaryRoots: string[] = [];

afterEach(() => {
	for (const root of temporaryRoots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function expectedVisualOwnerKeys(): readonly string[] {
	return MEADOW_ENTRY_BAKE_OWNERSHIP.filter(({ runtimeRequirement }) =>
		RUNTIME_REQUIREMENTS.has(runtimeRequirement)
	)
		.filter(({ ref }) => ref.sourceType !== 'blocker' || !SUNDROP_BLOCKER_IDS.has(ref.sourceId))
		.map(({ ref }) => `${ref.sourceType}:${ref.sourceId}`)
		.sort();
}

function ownerCropIds(sourceId: string): readonly string[] {
	const owner = collectMeadowEntryRuntimeData().visualOwners.find(
		(entry) => entry.sourceType === 'blocker' && entry.sourceId === sourceId
	);
	expect(owner).toBeDefined();
	return owner?.ownerCrops.map(({ cropId }) => cropId) ?? [];
}

describe('meadow-entry runtime data generation', () => {
	it('joins every approved export into the 22 browser-safe background rows', () => {
		const data = collectMeadowEntryRuntimeData();

		expect(data.backgrounds).toHaveLength(22);
		for (const approved of meadowEntryArtPackageApproval.exports) {
			const crop = MEADOW_ENTRY_APPROVED_CROPS.find(({ id }) => id === approved.cropId);
			if (!crop) throw new Error(`Missing approved crop ${approved.cropId}`);

			expect(data.backgrounds).toContainEqual({
				cropId: approved.cropId,
				id: `${approved.textureKey}-image`,
				textureKey: approved.textureKey,
				path: `/game/assets/regions/meadow-entry/${approved.path.split('/').at(-1)}`,
				x: (crop.bounds.left + crop.bounds.right) / 2,
				y: (crop.bounds.top + crop.bounds.bottom) / 2,
				width: approved.width,
				height: approved.height,
				plane: approved.plane,
				drawOrder: approved.drawOrder
			});
		}

		const rendered = renderMeadowEntryRuntimeData(data);
		expect(rendered).toMatch(
			/^\/\/ @generated by tools\/generate-meadow-entry-runtime\.ts\. Do not edit by hand\./
		);
		expect(rendered).toContain('MEADOW_ENTRY_APPROVED_RUNTIME_BACKGROUNDS');
		expect(rendered).toContain('MEADOW_ENTRY_RUNTIME_VISUAL_OWNERS');
		expect(rendered).not.toContain('primaryRegionId');
		expect(rendered).not.toContain('sourceRegionIds');
		expect(rendered).not.toContain('sha256');
	});

	it('includes every non-Sundrop fallback source in source-key order', () => {
		const actualKeys = collectMeadowEntryRuntimeData().visualOwners.map(
			({ sourceType, sourceId }) => `${sourceType}:${sourceId}`
		);

		expect(actualKeys).toEqual(expectedVisualOwnerKeys());
	});

	it('rejects byte-distinct generated output that decodes to the same UTF-8 text', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-meadow-runtime-'));
		temporaryRoots.push(root);
		const destination = join(root, 'meadow-entry-runtime.ts');
		writeFileSync(destination, Buffer.from([0xff]));

		expect(() => syncGeneratedMeadowEntryRuntimeData('\ufffd', destination, true)).toThrow(/stale/);
	});

	it('uses only the outer-boundary crop for the Wildwood forest-lane west bank', () => {
		expect(ownerCropIds('wildwood-forest-lane-west-bank')).toEqual([
			'outer-boundary-east-forest-lane'
		]);
	});

	it('retains both complete crops for the Wildwood north-climb east bank in draw-order order', () => {
		expect(ownerCropIds('wildwood-north-climb-east-bank')).toEqual([
			'outer-boundary-east-forest-lane',
			'wildwood'
		]);
	});
});
