import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it, vi } from 'vitest';

import {
	assertExactPathAllowlist,
	assertNoActivePublicationSentinels,
	compareFileTrees,
	parseLfsPointer,
	runValidationStages
} from '../../../../../tools/validate-meadow-entry-art-package';

const temporaryRoots: string[] = [];

async function temporaryRoot(): Promise<string> {
	const root = await mkdtemp(join(tmpdir(), 'gliese-meadow-entry-validator-'));
	temporaryRoots.push(root);
	return root;
}

afterEach(async () => {
	await Promise.all(
		temporaryRoots.splice(0).map((root) => rm(root, { recursive: true, force: true }))
	);
});

describe('Meadow Entry art package validator', () => {
	it('stops at the first failed validation stage', async () => {
		const visited: string[] = [];
		await expect(
			runValidationStages([
				{ name: 'first', run: async () => void visited.push('first') },
				{
					name: 'second',
					run: async () => {
						visited.push('second');
						throw new Error('expected failure');
					}
				},
				{ name: 'third', run: async () => void visited.push('third') }
			])
		).rejects.toThrow('second: expected failure');
		expect(visited).toEqual(['first', 'second']);
	});

	it('rejects malformed Git LFS pointers and parses the canonical form', () => {
		expect(
			parseLfsPointer(
				Buffer.from(
					'version https://git-lfs.github.com/spec/v1\noid sha256:' +
						'a'.repeat(64) +
						'\nsize 123\n'
				)
			)
		).toEqual({ oid: 'a'.repeat(64), size: 123 });
		expect(() => parseLfsPointer(Buffer.from('not a pointer\n'))).toThrow(
			/canonical Git LFS pointer/
		);
	});

	it('rejects missing and unexpected paths from fixed inventories', () => {
		expect(() => assertExactPathAllowlist('proof', ['a.png'], ['a.png'])).not.toThrow();
		expect(() => assertExactPathAllowlist('proof', ['a.png'], ['a.png', 'extra.png'])).toThrow(
			/proof path allowlist drifted.*unexpected=extra\.png/
		);
		expect(() => assertExactPathAllowlist('proof', ['a.png', 'b.png'], ['a.png'])).toThrow(
			/proof path allowlist drifted.*missing=b\.png/
		);
	});

	it('rejects every active publication sentinel', async () => {
		const root = await temporaryRoot();
		await mkdir(join(root, 'artifacts/meadow-entry/hpa-399'), { recursive: true });
		await writeFile(
			join(root, 'artifacts/meadow-entry/hpa-399/.meadow-entry-export-publication.lock'),
			'active\n'
		);
		await expect(assertNoActivePublicationSentinels(root)).rejects.toThrow(
			/Meadow Entry export publication is in progress/
		);
	});

	it('compares deterministic regeneration trees byte-for-byte', async () => {
		const expectedRoot = await temporaryRoot();
		const actualRoot = await temporaryRoot();
		await writeFile(join(expectedRoot, 'same.bin'), Buffer.from([0, 1, 2]));
		await writeFile(join(actualRoot, 'same.bin'), Buffer.from([0, 1, 2]));
		await expect(compareFileTrees('exports', expectedRoot, actualRoot)).resolves.toEqual({
			files: 1,
			bytes: 3
		});
		await writeFile(join(actualRoot, 'same.bin'), Buffer.from([0, 1, 3]));
		await expect(compareFileTrees('exports', expectedRoot, actualRoot)).rejects.toThrow(
			/exports regenerated byte drift: same\.bin/
		);
	});

	it('rejects Git LFS pointers whose size exceeds the safe integer range', () => {
		expect(() =>
			parseLfsPointer(
				Buffer.from(
					'version https://git-lfs.github.com/spec/v1\noid sha256:' +
						'a'.repeat(64) +
						'\nsize 9007199254740992\n'
				)
			)
		).toThrow(/size is invalid/);
	});

	it('parses Git LFS pointers with size 0', () => {
		expect(
			parseLfsPointer(
				Buffer.from(
					'version https://git-lfs.github.com/spec/v1\noid sha256:' + 'b'.repeat(64) + '\nsize 0\n'
				)
			)
		).toEqual({ oid: 'b'.repeat(64), size: 0 });
	});

	it('rejects duplicate expected paths in a fixed inventory', () => {
		expect(() => assertExactPathAllowlist('proof', ['a.png', 'a.png'], ['a.png'])).toThrow(
			/proof path allowlist drifted/
		);
	});

	it('rejects duplicate actual paths in a fixed inventory', () => {
		expect(() => assertExactPathAllowlist('proof', ['a.png'], ['a.png', 'a.png'])).toThrow(
			/proof path allowlist drifted/
		);
	});

	it('rejects the main publication sentinel', async () => {
		const root = await temporaryRoot();
		await mkdir(join(root, 'artifacts/meadow-entry/hpa-399'), { recursive: true });
		await writeFile(
			join(root, 'artifacts/meadow-entry/hpa-399/.meadow-entry-publication.lock'),
			'active\n'
		);
		await expect(assertNoActivePublicationSentinels(root)).rejects.toThrow(
			/Meadow Entry approved package publication is in progress/
		);
	});

	it('rejects the proof publication sentinel', async () => {
		const root = await temporaryRoot();
		await mkdir(join(root, 'docs/superpowers/reports/img/hpa-399'), { recursive: true });
		await writeFile(
			join(root, 'docs/superpowers/reports/img/hpa-399/.meadow-entry-proof-publication.lock'),
			'active\n'
		);
		await expect(assertNoActivePublicationSentinels(root)).rejects.toThrow(
			/Meadow Entry proof publication is in progress/
		);
	});

	it('reports missing files when the actual tree lacks an expected entry', async () => {
		const expectedRoot = await temporaryRoot();
		const actualRoot = await temporaryRoot();
		await writeFile(join(expectedRoot, 'only-expected.bin'), Buffer.from([0]));
		await expect(compareFileTrees('exports', expectedRoot, actualRoot)).rejects.toThrow(
			/exports path allowlist drifted.*missing=only-expected\.bin/
		);
	});

	it('reports unexpected files when the actual tree has an extra entry', async () => {
		const expectedRoot = await temporaryRoot();
		const actualRoot = await temporaryRoot();
		await writeFile(join(actualRoot, 'only-actual.bin'), Buffer.from([0]));
		await expect(compareFileTrees('exports', expectedRoot, actualRoot)).rejects.toThrow(
			/exports path allowlist drifted.*unexpected=only-actual\.bin/
		);
	});

	it('walks nested directory structures byte-for-byte', async () => {
		const expectedRoot = await temporaryRoot();
		const actualRoot = await temporaryRoot();
		await mkdir(join(expectedRoot, 'nested/deep'), { recursive: true });
		await mkdir(join(actualRoot, 'nested/deep'), { recursive: true });
		await writeFile(join(expectedRoot, 'nested/top.bin'), Buffer.from([1, 2]));
		await writeFile(join(actualRoot, 'nested/top.bin'), Buffer.from([1, 2]));
		await writeFile(join(expectedRoot, 'nested/deep/leaf.bin'), Buffer.from([3, 4, 5]));
		await writeFile(join(actualRoot, 'nested/deep/leaf.bin'), Buffer.from([3, 4, 5]));
		await expect(compareFileTrees('exports', expectedRoot, actualRoot)).resolves.toEqual({
			files: 2,
			bytes: 5
		});
	});

	it('runs every validation stage and reports names with positive durations', async () => {
		const writeSpy = vi.spyOn(process.stdout, 'write').mockImplementation(() => true);
		try {
			const results = await runValidationStages([
				{ name: 'alpha', run: async () => undefined },
				{ name: 'beta', run: async () => undefined },
				{ name: 'gamma', run: async () => undefined }
			]);
			expect(results.map((result) => result.name)).toEqual(['alpha', 'beta', 'gamma']);
			for (const result of results) {
				expect(result.durationMs).toBeGreaterThanOrEqual(0);
			}
			expect(writeSpy).toHaveBeenCalled();
		} finally {
			writeSpy.mockRestore();
		}
	});

	it('wraps stage failures with the stage name prefix and preserves the cause', async () => {
		const cause = new Error('underlying failure');
		await expect(
			runValidationStages([
				{
					name: 'failing-stage',
					run: async () => {
						throw cause;
					}
				}
			])
		).rejects.toThrow('failing-stage: underlying failure');
		try {
			await runValidationStages([
				{
					name: 'failing-stage',
					run: async () => {
						throw cause;
					}
				}
			]);
		} catch (error) {
			expect((error as Error).cause).toBe(cause);
		}
	});
});
