import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import { meadowEntryArtPackageApproval } from '$lib/game/content/approvals/meadow-entry-art-package';
import { MEADOW_ENTRY_BAKE_OWNERSHIP } from '$lib/game/content/backgrounds/meadow-entry-bake-ownership';
import { MEADOW_ENTRY_APPROVED_CROPS } from '$lib/game/content/backgrounds/meadow-entry-crop-manifest';

import {
	type MeadowEntryRuntimeData,
	type MeadowEntryRuntimeGenerationInput,
	collectMeadowEntryRuntimeData,
	MEADOW_ENTRY_PAINTED_V2_RUNTIME_GENERATION_INPUT,
	parseCheckMode,
	renderMeadowEntryRuntimeData,
	runMeadowEntryRuntimeGenerator,
	syncGeneratedMeadowEntryRuntimeData
} from '../../../../../tools/generate-meadow-entry-runtime';

const RUNTIME_REQUIREMENTS = new Set([
	'existing-blocker-fallback',
	'extend-decor-fallback',
	'extend-fence-fallback'
]);
const temporaryRoots: string[] = [];

const HISTORICAL_GENERATION_INPUT: MeadowEntryRuntimeGenerationInput = {
	crops: MEADOW_ENTRY_APPROVED_CROPS,
	bakeOwnership: MEADOW_ENTRY_BAKE_OWNERSHIP,
	approvedExports: meadowEntryArtPackageApproval.exports,
	runtimeRoot: 'public/game/assets/regions/meadow-entry'
};

afterEach(() => {
	for (const root of temporaryRoots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function expectedVisualOwnerKeys(): readonly string[] {
	return MEADOW_ENTRY_BAKE_OWNERSHIP.filter(({ runtimeRequirement }) =>
		RUNTIME_REQUIREMENTS.has(runtimeRequirement)
	)
		.map(({ ref }) => `${ref.sourceType}:${ref.sourceId}`)
		.sort();
}

function ownerCropIds(sourceId: string): readonly string[] {
	const owner = collectMeadowEntryRuntimeData(HISTORICAL_GENERATION_INPUT).visualOwners.find(
		(entry) => entry.sourceType === 'blocker' && entry.sourceId === sourceId
	);
	expect(owner).toBeDefined();
	return owner?.ownerCrops.map(({ cropId }) => cropId) ?? [];
}

describe('meadow-entry runtime data generation', () => {
	it('joins every approved export into the 22 browser-safe background rows', () => {
		const data = collectMeadowEntryRuntimeData(HISTORICAL_GENERATION_INPUT);

		expect(data.backgrounds).toHaveLength(22);
		for (const approved of meadowEntryArtPackageApproval.exports) {
			const crop = MEADOW_ENTRY_APPROVED_CROPS.find(({ id }) => id === approved.cropId);
			if (!crop) throw new Error(`Missing approved crop ${approved.cropId}`);

			expect(data.backgrounds).toContainEqual({
				cropId: approved.cropId,
				id: `${approved.textureKey}-image`,
				textureKey: approved.textureKey,
				path: `/game/assets/regions/meadow-entry/${approved.path.split('/').at(-1)}`,
				x: (crop.bounds.left + crop.bounds.right) / 2,
				y: (crop.bounds.top + crop.bounds.bottom) / 2,
				width: approved.width,
				height: approved.height,
				plane: approved.plane,
				drawOrder: approved.drawOrder
			});
		}

		const rendered = renderMeadowEntryRuntimeData(data);
		expect(rendered).toMatch(
			/^\/\/ @generated by tools\/generate-meadow-entry-runtime\.ts\. Do not edit by hand\./
		);
		expect(rendered).toContain('MEADOW_ENTRY_PAINTED_V2_APPROVED_RUNTIME_BACKGROUNDS');
		expect(rendered).toContain('MEADOW_ENTRY_PAINTED_V2_RUNTIME_VISUAL_OWNERS');
		expect(rendered).not.toContain('primaryRegionId');
		expect(rendered).not.toContain('sourceRegionIds');
		expect(rendered).not.toContain('sha256');
	});

	it('includes every non-Sundrop fallback source in source-key order', () => {
		const actualKeys = collectMeadowEntryRuntimeData(HISTORICAL_GENERATION_INPUT).visualOwners.map(
			({ sourceType, sourceId }) => `${sourceType}:${sourceId}`
		);

		expect(actualKeys).toEqual(expectedVisualOwnerKeys());
	});

	it('rejects byte-distinct generated output that decodes to the same UTF-8 text', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-meadow-runtime-'));
		temporaryRoots.push(root);
		const destination = join(root, 'meadow-entry-runtime.ts');
		writeFileSync(destination, Buffer.from([0xff]));

		expect(() => syncGeneratedMeadowEntryRuntimeData('\ufffd', destination, true)).toThrow(/stale/);
	});

	it('uses only the outer-boundary crop for the Wildwood forest-lane west bank', () => {
		expect(ownerCropIds('wildwood-forest-lane-west-bank')).toEqual([
			'outer-boundary-east-forest-lane'
		]);
	});

	it('retains both complete crops for the Wildwood north-climb east bank in draw-order order', () => {
		expect(ownerCropIds('wildwood-north-climb-east-bank')).toEqual([
			'outer-boundary-east-forest-lane',
			'wildwood'
		]);
	});
});

describe('parseCheckMode', () => {
	it('returns false when no arguments are provided', () => {
		expect(parseCheckMode([])).toBe(false);
	});

	it('returns true when --check is the sole argument', () => {
		expect(parseCheckMode(['--check'])).toBe(true);
	});

	it('throws when an unknown argument is provided', () => {
		expect(() => parseCheckMode(['--unknown'])).toThrow(/Usage:/);
	});

	it('throws when --check is combined with extra arguments', () => {
		expect(() => parseCheckMode(['--check', '--extra'])).toThrow(/Usage:/);
	});
});

describe('runMeadowEntryRuntimeGenerator', () => {
	it('writes the generated runtime data file in default mode', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-meadow-runtime-write-'));
		temporaryRoots.push(root);

		runMeadowEntryRuntimeGenerator([], root);

		const destination = join(
			root,
			'src/lib/game/content/backgrounds/meadow-entry-painted-v2.generated.ts'
		);
		expect(existsSync(destination)).toBe(true);

		const expected = renderMeadowEntryRuntimeData(
			collectMeadowEntryRuntimeData(MEADOW_ENTRY_PAINTED_V2_RUNTIME_GENERATION_INPUT)
		);
		expect(readFileSync(destination, 'utf8')).toBe(expected);
	});

	it('passes when --check matches the current generated data', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-meadow-runtime-check-ok-'));
		temporaryRoots.push(root);

		runMeadowEntryRuntimeGenerator([], root);
		expect(() => runMeadowEntryRuntimeGenerator(['--check'], root)).not.toThrow();
	});

	it('throws when --check finds a stale generated file', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-meadow-runtime-check-stale-'));
		temporaryRoots.push(root);
		const destination = join(
			root,
			'src/lib/game/content/backgrounds/meadow-entry-painted-v2.generated.ts'
		);

		runMeadowEntryRuntimeGenerator([], root);
		writeFileSync(destination, 'stale content');

		expect(() => runMeadowEntryRuntimeGenerator(['--check'], root)).toThrow(/stale/);
	});

	it('throws when --check finds the generated file missing', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-meadow-runtime-check-missing-'));
		temporaryRoots.push(root);

		expect(() => runMeadowEntryRuntimeGenerator(['--check'], root)).toThrow(/missing/);
	});
});

describe('syncGeneratedMeadowEntryRuntimeData write path', () => {
	it('atomically writes the source to the destination path', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-meadow-sync-write-'));
		temporaryRoots.push(root);
		const destination = join(root, 'output.ts');

		syncGeneratedMeadowEntryRuntimeData('hello world', destination, false);

		expect(existsSync(destination)).toBe(true);
		expect(readFileSync(destination, 'utf8')).toBe('hello world');
	});

	it('creates parent directories as needed', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-meadow-sync-mkdir-'));
		temporaryRoots.push(root);
		const destination = join(root, 'nested', 'dir', 'output.ts');

		syncGeneratedMeadowEntryRuntimeData('content', destination, false);

		expect(existsSync(destination)).toBe(true);
		expect(readFileSync(destination, 'utf8')).toBe('content');
	});

	it('overwrites an existing destination file', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-meadow-sync-overwrite-'));
		temporaryRoots.push(root);
		const destination = join(root, 'output.ts');
		writeFileSync(destination, 'old content');

		syncGeneratedMeadowEntryRuntimeData('new content', destination, false);

		expect(readFileSync(destination, 'utf8')).toBe('new content');
	});
});

describe('renderMeadowEntryRuntimeData inline string-array path', () => {
	it('renders requiredBackgroundIds inline when the line fits within 100 chars', () => {
		const inlineData: MeadowEntryRuntimeData = {
			backgrounds: [],
			visualOwners: [
				{
					sourceType: 'blocker',
					sourceId: 'x',
					ownerCrops: [
						{
							cropId: 'a',
							requiredBackgroundIds: ['b-image']
						}
					]
				}
			]
		};

		const rendered = renderMeadowEntryRuntimeData(inlineData);
		expect(rendered).toContain("requiredBackgroundIds: ['b-image']");
	});

	it('renders requiredBackgroundIds across multiple lines when the inline form exceeds 100 chars', () => {
		const longId = `meadow-entry-${'x'.repeat(60)}-base-image`;
		const multilineData: MeadowEntryRuntimeData = {
			backgrounds: [],
			visualOwners: [
				{
					sourceType: 'decor',
					sourceId: 'y',
					ownerCrops: [
						{
							cropId: 'c',
							requiredBackgroundIds: [longId]
						}
					]
				}
			]
		};

		const rendered = renderMeadowEntryRuntimeData(multilineData);
		expect(rendered).not.toContain(`requiredBackgroundIds: ['${longId}']`);
		expect(rendered).toContain('requiredBackgroundIds: [');
		expect(rendered).toContain(`'${longId}'`);
	});
});
