// @generated by tools/generate-meadow-entry-runtime.ts. Do not edit by hand.

import type { MapBackgroundImage, MapVisualOwnerCrop } from '$lib/game/content/maps/types';

export interface GeneratedMeadowEntryBackground extends MapBackgroundImage {
	readonly cropId: string;
	readonly path: string;
}

export interface GeneratedMeadowEntryVisualOwner {
	readonly sourceType: 'blocker' | 'decor' | 'fence';
	readonly sourceId: string;
	readonly ownerCrops: readonly MapVisualOwnerCrop[];
}

export const MEADOW_ENTRY_PAINTED_V2_APPROVED_RUNTIME_BACKGROUNDS = [
	{
		cropId: 'painted-v2-sundrop-camera-base',
		id: 'meadow-entry-painted-v2-sundrop-camera-base-image',
		textureKey: 'meadow-entry-painted-v2-sundrop-camera-base',
		path: '/game/assets/regions/meadow-entry-painted-v2/painted-v2-sundrop-camera-base.png',
		x: 1600,
		y: 4800,
		width: 3200,
		height: 3200,
		plane: 'base',
		drawOrder: 0
	},
	{
		cropId: 'painted-v2-crossroads-camera-base',
		id: 'meadow-entry-painted-v2-crossroads-camera-base-image',
		textureKey: 'meadow-entry-painted-v2-crossroads-camera-base',
		path: '/game/assets/regions/meadow-entry-painted-v2/painted-v2-crossroads-camera-base.png',
		x: 3968,
		y: 3840,
		width: 3200,
		height: 3200,
		plane: 'base',
		drawOrder: 10
	}
] as const satisfies readonly GeneratedMeadowEntryBackground[];

export const MEADOW_ENTRY_PAINTED_V2_RUNTIME_VISUAL_OWNERS = [
	{
		sourceType: 'blocker',
		sourceId: 'silverpine-wall-B-south',
		ownerCrops: [
			{
				cropId: 'painted-v2-crossroads-camera-base',
				requiredBackgroundIds: ['meadow-entry-painted-v2-crossroads-camera-base-image']
			}
		]
	},
	{
		sourceType: 'decor',
		sourceId: 'village-decor-22-77',
		ownerCrops: [
			{
				cropId: 'painted-v2-sundrop-camera-base',
				requiredBackgroundIds: ['meadow-entry-painted-v2-sundrop-camera-base-image']
			},
			{
				cropId: 'painted-v2-crossroads-camera-base',
				requiredBackgroundIds: ['meadow-entry-painted-v2-crossroads-camera-base-image']
			}
		]
	},
	{
		sourceType: 'decor',
		sourceId: 'village-decor-28-25',
		ownerCrops: [
			{
				cropId: 'painted-v2-sundrop-camera-base',
				requiredBackgroundIds: ['meadow-entry-painted-v2-sundrop-camera-base-image']
			}
		]
	},
	{
		sourceType: 'decor',
		sourceId: 'village-decor-28-53',
		ownerCrops: [
			{
				cropId: 'painted-v2-sundrop-camera-base',
				requiredBackgroundIds: ['meadow-entry-painted-v2-sundrop-camera-base-image']
			}
		]
	},
	{
		sourceType: 'decor',
		sourceId: 'village-decor-53-22',
		ownerCrops: [
			{
				cropId: 'painted-v2-sundrop-camera-base',
				requiredBackgroundIds: ['meadow-entry-painted-v2-sundrop-camera-base-image']
			}
		]
	}
] as const satisfies readonly GeneratedMeadowEntryVisualOwner[];
