// @generated by tools/generate-meadow-entry-runtime.ts. Do not edit by hand.

import type { MapBackgroundImage, MapVisualOwnerCrop } from '$lib/game/content/maps/types';

export interface GeneratedMeadowEntryBackground extends MapBackgroundImage {
	readonly cropId: string;
	readonly path: string;
}

export interface GeneratedMeadowEntryVisualOwner {
	readonly sourceType: 'blocker' | 'decor' | 'fence';
	readonly sourceId: string;
	readonly ownerCrops: readonly MapVisualOwnerCrop[];
}

export const MEADOW_ENTRY_PAINTED_V2_COMPLETE_APPROVED_RUNTIME_BACKGROUNDS = [
	{
		cropId: 'painted-v2-complete-northwest',
		id: 'meadow-entry-painted-v2-complete-northwest-base-image',
		textureKey: 'meadow-entry-painted-v2-complete-northwest-base',
		path: '/game/assets/regions/meadow-entry-painted-v2/painted-v2-complete-northwest-base.png',
		x: 1600,
		y: 1600,
		width: 3200,
		height: 3200,
		plane: 'base',
		drawOrder: 0
	},
	{
		cropId: 'painted-v2-complete-northeast',
		id: 'meadow-entry-painted-v2-complete-northeast-base-image',
		textureKey: 'meadow-entry-painted-v2-complete-northeast-base',
		path: '/game/assets/regions/meadow-entry-painted-v2/painted-v2-complete-northeast-base.png',
		x: 4800,
		y: 1600,
		width: 3200,
		height: 3200,
		plane: 'base',
		drawOrder: 10
	},
	{
		cropId: 'painted-v2-complete-southwest',
		id: 'meadow-entry-painted-v2-complete-southwest-base-image',
		textureKey: 'meadow-entry-painted-v2-complete-southwest-base',
		path: '/game/assets/regions/meadow-entry-painted-v2/painted-v2-complete-southwest-base.png',
		x: 1600,
		y: 4800,
		width: 3200,
		height: 3200,
		plane: 'base',
		drawOrder: 20
	},
	{
		cropId: 'painted-v2-complete-southeast',
		id: 'meadow-entry-painted-v2-complete-southeast-base-image',
		textureKey: 'meadow-entry-painted-v2-complete-southeast-base',
		path: '/game/assets/regions/meadow-entry-painted-v2/painted-v2-complete-southeast-base.png',
		x: 4800,
		y: 4800,
		width: 3200,
		height: 3200,
		plane: 'base',
		drawOrder: 30
	}
] as const satisfies readonly GeneratedMeadowEntryBackground[];

export const MEADOW_ENTRY_PAINTED_V2_COMPLETE_RUNTIME_VISUAL_OWNERS =
	[] as const satisfies readonly GeneratedMeadowEntryVisualOwner[];
