// @generated by tools/generate-meadow-entry-runtime.ts. Do not edit by hand.

import type { MapBackgroundImage, MapVisualOwnerCrop } from '$lib/game/content/maps/types';

export interface GeneratedMeadowEntryBackground extends MapBackgroundImage {
	readonly cropId: string;
	readonly path: string;
}

export interface GeneratedMeadowEntryVisualOwner {
	readonly sourceType: 'blocker' | 'decor' | 'fence';
	readonly sourceId: string;
	readonly ownerCrops: readonly MapVisualOwnerCrop[];
}

export const MEADOW_ENTRY_PAINTED_V2_APPROVED_RUNTIME_BACKGROUNDS = [
	{
		cropId: 'painted-v2-sundrop-village',
		id: 'meadow-entry-painted-v2-sundrop-village-base-image',
		textureKey: 'meadow-entry-painted-v2-sundrop-village-base',
		path: '/game/assets/regions/meadow-entry-painted-v2/painted-v2-sundrop-village-base.png',
		x: 1568,
		y: 5056,
		width: 2624,
		height: 2176,
		plane: 'base',
		drawOrder: 0
	},
	{
		cropId: 'painted-v2-village-crossroads-connector',
		id: 'meadow-entry-painted-v2-village-crossroads-connector-base-image',
		textureKey: 'meadow-entry-painted-v2-village-crossroads-connector-base',
		path: '/game/assets/regions/meadow-entry-painted-v2/painted-v2-village-crossroads-connector-base.png',
		x: 2992,
		y: 4688,
		width: 800,
		height: 416,
		plane: 'base',
		drawOrder: 10
	},
	{
		cropId: 'painted-v2-crossroads',
		id: 'meadow-entry-painted-v2-crossroads-base-image',
		textureKey: 'meadow-entry-painted-v2-crossroads-base',
		path: '/game/assets/regions/meadow-entry-painted-v2/painted-v2-crossroads-base.png',
		x: 3744,
		y: 3792,
		width: 1728,
		height: 1952,
		plane: 'base',
		drawOrder: 20
	}
] as const satisfies readonly GeneratedMeadowEntryBackground[];

export const MEADOW_ENTRY_PAINTED_V2_RUNTIME_VISUAL_OWNERS = [
	{
		sourceType: 'blocker',
		sourceId: 'silverpine-wall-B-south',
		ownerCrops: [
			{
				cropId: 'painted-v2-crossroads',
				requiredBackgroundIds: ['meadow-entry-painted-v2-crossroads-base-image']
			}
		]
	},
	{
		sourceType: 'decor',
		sourceId: 'village-decor-22-77',
		ownerCrops: [
			{
				cropId: 'painted-v2-sundrop-village',
				requiredBackgroundIds: ['meadow-entry-painted-v2-sundrop-village-base-image']
			},
			{
				cropId: 'painted-v2-village-crossroads-connector',
				requiredBackgroundIds: ['meadow-entry-painted-v2-village-crossroads-connector-base-image']
			}
		]
	},
	{
		sourceType: 'decor',
		sourceId: 'village-decor-28-25',
		ownerCrops: [
			{
				cropId: 'painted-v2-sundrop-village',
				requiredBackgroundIds: ['meadow-entry-painted-v2-sundrop-village-base-image']
			}
		]
	},
	{
		sourceType: 'decor',
		sourceId: 'village-decor-28-53',
		ownerCrops: [
			{
				cropId: 'painted-v2-sundrop-village',
				requiredBackgroundIds: ['meadow-entry-painted-v2-sundrop-village-base-image']
			}
		]
	},
	{
		sourceType: 'decor',
		sourceId: 'village-decor-53-22',
		ownerCrops: [
			{
				cropId: 'painted-v2-sundrop-village',
				requiredBackgroundIds: ['meadow-entry-painted-v2-sundrop-village-base-image']
			}
		]
	}
] as const satisfies readonly GeneratedMeadowEntryVisualOwner[];
