import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import {
	assertExactPathAllowlist,
	assertNoActivePublicationSentinels,
	compareFileTrees,
	parseLfsPointer,
	runValidationStages
} from '../../../../../tools/validate-meadow-entry-art-package';

const temporaryRoots: string[] = [];

async function temporaryRoot(): Promise<string> {
	const root = await mkdtemp(join(tmpdir(), 'gliese-meadow-entry-validator-'));
	temporaryRoots.push(root);
	return root;
}

afterEach(async () => {
	await Promise.all(
		temporaryRoots.splice(0).map((root) => rm(root, { recursive: true, force: true }))
	);
});

describe('Meadow Entry art package validator', () => {
	it('stops at the first failed validation stage', async () => {
		const visited: string[] = [];
		await expect(
			runValidationStages([
				{ name: 'first', run: async () => void visited.push('first') },
				{
					name: 'second',
					run: async () => {
						visited.push('second');
						throw new Error('expected failure');
					}
				},
				{ name: 'third', run: async () => void visited.push('third') }
			])
		).rejects.toThrow('second: expected failure');
		expect(visited).toEqual(['first', 'second']);
	});

	it('rejects malformed Git LFS pointers and parses the canonical form', () => {
		expect(
			parseLfsPointer(
				Buffer.from(
					'version https://git-lfs.github.com/spec/v1\noid sha256:' +
						'a'.repeat(64) +
						'\nsize 123\n'
				)
			)
		).toEqual({ oid: 'a'.repeat(64), size: 123 });
		expect(() => parseLfsPointer(Buffer.from('not a pointer\n'))).toThrow(
			/canonical Git LFS pointer/
		);
	});

	it('rejects missing and unexpected paths from fixed inventories', () => {
		expect(() => assertExactPathAllowlist('proof', ['a.png'], ['a.png'])).not.toThrow();
		expect(() => assertExactPathAllowlist('proof', ['a.png'], ['a.png', 'extra.png'])).toThrow(
			/proof path allowlist drifted.*unexpected=extra\.png/
		);
		expect(() => assertExactPathAllowlist('proof', ['a.png', 'b.png'], ['a.png'])).toThrow(
			/proof path allowlist drifted.*missing=b\.png/
		);
	});

	it('rejects every active publication sentinel', async () => {
		const root = await temporaryRoot();
		await mkdir(join(root, 'artifacts/meadow-entry/hpa-399'), { recursive: true });
		await writeFile(
			join(root, 'artifacts/meadow-entry/hpa-399/.meadow-entry-export-publication.lock'),
			'active\n'
		);
		await expect(assertNoActivePublicationSentinels(root)).rejects.toThrow(
			/Meadow Entry export publication is in progress/
		);
	});

	it('compares deterministic regeneration trees byte-for-byte', async () => {
		const expectedRoot = await temporaryRoot();
		const actualRoot = await temporaryRoot();
		await writeFile(join(expectedRoot, 'same.bin'), Buffer.from([0, 1, 2]));
		await writeFile(join(actualRoot, 'same.bin'), Buffer.from([0, 1, 2]));
		await expect(compareFileTrees('exports', expectedRoot, actualRoot)).resolves.toEqual({
			files: 1,
			bytes: 3
		});
		await writeFile(join(actualRoot, 'same.bin'), Buffer.from([0, 1, 3]));
		await expect(compareFileTrees('exports', expectedRoot, actualRoot)).rejects.toThrow(
			/exports regenerated byte drift: same\.bin/
		);
	});
});
