export const SUNDROP_VILLAGE_BASE_BACKGROUND_ID = 'sundrop-village-base-image';
export const SUNDROP_VILLAGE_FOREGROUND_BACKGROUND_ID = 'sundrop-village-foreground-image';

export const SUNDROP_VILLAGE_BASE_BACKGROUND_TEXTURE_KEY = 'sundrop-village-base';
export const SUNDROP_VILLAGE_FOREGROUND_BACKGROUND_TEXTURE_KEY = 'sundrop-village-foreground';

export const SUNDROP_VILLAGE_BASE_BACKGROUND_PATH = '/game/assets/regions/sundrop-village-base.png';
export const SUNDROP_VILLAGE_FOREGROUND_BACKGROUND_PATH =
	'/game/assets/regions/sundrop-village-foreground.png';

export const SUNDROP_VILLAGE_BACKGROUND_WIDTH = 1792;
export const SUNDROP_VILLAGE_BACKGROUND_HEIGHT = 1536;
export const SUNDROP_VILLAGE_BASE_BACKGROUND_REVIEW_TARGET_BYTES = 4_194_304;
export const SUNDROP_VILLAGE_BASE_BACKGROUND_HARD_LIMIT_BYTES = 8_388_608;
export const SUNDROP_VILLAGE_FOREGROUND_BACKGROUND_REVIEW_TARGET_BYTES = 2_097_152;
export const SUNDROP_VILLAGE_FOREGROUND_BACKGROUND_HARD_LIMIT_BYTES = 4_194_304;
export const SUNDROP_VILLAGE_BACKGROUND_COMBINED_HARD_LIMIT_BYTES = 12_582_912;
export const SUNDROP_VILLAGE_FOREGROUND_FRONT_CUTOFF_PX = 33;
