/** Generated by tools/approve-meadow-entry-controls.ts from reviewed checked-in controls. */
export interface MeadowEntryControlsApproval {
	combinedControlFingerprint: string;
	cropManifestSha256: string;
	bakeOwnershipSha256: string;
	storageMode: 'git-lfs';
	storageConfigurationSha256: string;
	evidencePath: 'docs/superpowers/reports/2026-08-12-meadow-entry-painted-camera-safe-controls.md';
}

export const meadowEntryControlsApprovalReview = {
	reviewedBy: 'chanwaichan',
	reviewedAt: '2026-08-13T16:19:16Z'
} as const;

export const meadowEntryControlsApproval: MeadowEntryControlsApproval = {
	combinedControlFingerprint: '0916ae390990efcc7fc5ec6df5045b07c9b472cc54cb58625293bcb8445ca6cf',
	cropManifestSha256: '481980a8cb3c26e305657577404001d85672bbd1cf336001165abccc128338e6',
	bakeOwnershipSha256: 'bd9624b2b761e2071d9d45c1c556e71c05c3298cec8439db3220aa8eb2ed3e8e',
	storageMode: 'git-lfs',
	storageConfigurationSha256: '36737b6905cfc7c62fdf1bcdd48850bc574f20d7f4bfb63ab1aa8c727bc51de2',
	evidencePath: 'docs/superpowers/reports/2026-08-12-meadow-entry-painted-camera-safe-controls.md'
};
