/** Generated by tools/approve-meadow-entry-controls.ts from reviewed checked-in controls. */
export interface MeadowEntryControlsApproval {
	combinedControlFingerprint: string;
	cropManifestSha256: string;
	bakeOwnershipSha256: string;
	storageMode: 'git-lfs';
	storageConfigurationSha256: string;
	evidencePath: 'docs/superpowers/reports/2026-07-30-hpa-399-controls-crops-storage-validation.md';
}

export const meadowEntryControlsApprovalReview = {
	reviewedBy: 'chanwaichan',
	reviewedAt: '2026-08-01T04:30:44Z'
} as const;

export const meadowEntryControlsApproval: MeadowEntryControlsApproval = {
	combinedControlFingerprint: 'f42f7f0c558d40fd60b9b6700bfccaad115641ef77a859891a0ecc0151b0d4be',
	cropManifestSha256: 'c3ff227bef6206d2677e0bf42aa2c91b647ea6412428451ec5dbcf72975d3cca',
	bakeOwnershipSha256: 'b5a51c65596eb2798d8b88223738b7aae5d596c5c9ce9e50150859e92a87e198',
	storageMode: 'git-lfs',
	storageConfigurationSha256: '0cf1316ca427ce34ff4480a8ce9f7d78bcaf9305b40ad7b699b8a4891ce80997',
	evidencePath: 'docs/superpowers/reports/2026-07-30-hpa-399-controls-crops-storage-validation.md'
};
