/** Generated by tools/approve-meadow-entry-art-package.ts from the reviewed fixed inventory. */
export interface ApprovedPngArtifact {
	path: string;
	sha256: string;
	bytes: number;
	width: number;
	height: number;
}

export interface MeadowEntryArtPackageApproval {
	combinedControlFingerprint: string;
	storageMode: 'git-lfs';
	storageConfigurationSha256: string;
	baseMaster: ApprovedPngArtifact;
	foregroundMaster: ApprovedPngArtifact;
	cropManifestSha256: string;
	masterProvenanceSha256: string;
	exportProvenanceSha256: string;
	exports: readonly (ApprovedPngArtifact & {
		cropId: string;
		plane: 'base' | 'foreground';
		textureKey: string;
		drawOrder: number;
	})[];
	proofs: readonly (ApprovedPngArtifact & {
		proofId: string;
		inputSha256: readonly string[];
	})[];
	evidencePath: 'docs/superpowers/reports/2026-07-30-hpa-399-visual-masters-exports-validation.md';
}

export const meadowEntryArtPackageApprovalReview = {
	reviewedBy: 'chanwaichan',
	reviewedAt: '2026-08-02T08:51:49Z'
} as const;

export const meadowEntryArtPackageApproval: MeadowEntryArtPackageApproval = {
	combinedControlFingerprint: 'a877c70797d303dee292582b715d009dfccace19f769ebbef86230b1fd17f26d',
	storageMode: 'git-lfs',
	storageConfigurationSha256: '0cf1316ca427ce34ff4480a8ce9f7d78bcaf9305b40ad7b699b8a4891ce80997',
	baseMaster: {
		path: 'artifacts/meadow-entry/hpa-399/masters/meadow-entry-base-master.png',
		sha256: '9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
		bytes: 75418273,
		width: 6400,
		height: 6400
	},
	foregroundMaster: {
		path: 'artifacts/meadow-entry/hpa-399/masters/meadow-entry-foreground-master.png',
		sha256: 'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
		bytes: 1498345,
		width: 6400,
		height: 6400
	},
	cropManifestSha256: '9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab',
	masterProvenanceSha256: '3cf4f7bf29659750ba776ba132a702f67a0f4fa3c74c6273102a42d934feffe3',
	exportProvenanceSha256: '8dfb2ee0578efd0fe6d036817d8c5a95ca04ca9603447663281d0d5a65936be8',
	exports: [
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/sundrop-village-underlay-base.png',
			sha256: '8367ce51ee8c216e66048eb8279e750962a4ba79a36a1136738ef40867c95115',
			bytes: 7497766,
			width: 1792,
			height: 1536,
			cropId: 'sundrop-village-underlay',
			plane: 'base',
			textureKey: 'meadow-entry-sundrop-village-underlay-base',
			drawOrder: 0
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/outer-boundary-east-forest-lane-base.png',
			sha256: 'ddbc722719d67ee2e1101c7ebbccb3ab8a78e5374114a23067a99e498e74e2cc',
			bytes: 12196325,
			width: 1440,
			height: 4608,
			cropId: 'outer-boundary-east-forest-lane',
			plane: 'base',
			textureKey: 'meadow-entry-outer-boundary-east-forest-lane-base',
			drawOrder: 10
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/village-crossroads-connector-base.png',
			sha256: '1875020048ae66971061ea5e1c4d69f8682c82a6e35c5ef75af1aed8a671dd6b',
			bytes: 5737991,
			width: 1920,
			height: 1376,
			cropId: 'village-crossroads-connector',
			plane: 'base',
			textureKey: 'meadow-entry-village-crossroads-connector-base',
			drawOrder: 100
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/village-crossroads-connector-foreground.png',
			sha256: '21a1ee9d6c354d00782eb0583917dc92b07733ab3e2502da0b9e80934ed352ea',
			bytes: 198795,
			width: 1920,
			height: 1376,
			cropId: 'village-crossroads-connector',
			plane: 'foreground',
			textureKey: 'meadow-entry-village-crossroads-connector-foreground',
			drawOrder: 100
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/crossroads-coast-connector-base.png',
			sha256: '7d7b5ccbd98c928eea4c5c464d849780db59b7b1e6902fd2b0e3ceea8453faac',
			bytes: 3055296,
			width: 1184,
			height: 1280,
			cropId: 'crossroads-coast-connector',
			plane: 'base',
			textureKey: 'meadow-entry-crossroads-coast-connector-base',
			drawOrder: 110
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/crossroads-coast-connector-foreground.png',
			sha256: '75743509b8120ee767c27723b8dfc04cd868c8050c09efab020100c65ffa3727',
			bytes: 114385,
			width: 1184,
			height: 1280,
			cropId: 'crossroads-coast-connector',
			plane: 'foreground',
			textureKey: 'meadow-entry-crossroads-coast-connector-foreground',
			drawOrder: 110
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/crossroads-mistfen-connector-base.png',
			sha256: '564036dc1bf04b3af970664d114f8bb0f32072588f90ada73c9835aca608e9ab',
			bytes: 2847019,
			width: 1088,
			height: 1280,
			cropId: 'crossroads-mistfen-connector',
			plane: 'base',
			textureKey: 'meadow-entry-crossroads-mistfen-connector-base',
			drawOrder: 120
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/crossroads-mistfen-connector-foreground.png',
			sha256: '16a0775fc314561d6a99e1e8eff69f555ff415d2e7878fa4d7a793c894401c52',
			bytes: 23556,
			width: 1088,
			height: 1280,
			cropId: 'crossroads-mistfen-connector',
			plane: 'foreground',
			textureKey: 'meadow-entry-crossroads-mistfen-connector-foreground',
			drawOrder: 120
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/crossroads-silverpine-connector-base.png',
			sha256: '71cb8b34953b34f57c099c26b1a45961dbeff3ec60b7d07b795672d12f48702d',
			bytes: 855497,
			width: 800,
			height: 480,
			cropId: 'crossroads-silverpine-connector',
			plane: 'base',
			textureKey: 'meadow-entry-crossroads-silverpine-connector-base',
			drawOrder: 130
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/crossroads-silverpine-connector-foreground.png',
			sha256: '2cf1cd7763691c40abc007801ea82f49969f87c504733002bc2469d496ef8542',
			bytes: 7452,
			width: 800,
			height: 480,
			cropId: 'crossroads-silverpine-connector',
			plane: 'foreground',
			textureKey: 'meadow-entry-crossroads-silverpine-connector-foreground',
			drawOrder: 130
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/crossroads-wildwood-connector-base.png',
			sha256: 'c5be6d9e8ea6c9acefa82cac34caac5995aff51117d572ba0e95f94f068991c0',
			bytes: 1907478,
			width: 640,
			height: 1472,
			cropId: 'crossroads-wildwood-connector',
			plane: 'base',
			textureKey: 'meadow-entry-crossroads-wildwood-connector-base',
			drawOrder: 140
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/crossroads-wildwood-connector-foreground.png',
			sha256: '3549f849229c20c892ac66f4f8247cf6d247f64a319d825923d2008e55572fa6',
			bytes: 13003,
			width: 640,
			height: 1472,
			cropId: 'crossroads-wildwood-connector',
			plane: 'foreground',
			textureKey: 'meadow-entry-crossroads-wildwood-connector-foreground',
			drawOrder: 140
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/crossroads-base.png',
			sha256: '241671fd530810cc95ec20665eacd3f7080501691e912694f68f2a20963d0949',
			bytes: 7589332,
			width: 1600,
			height: 2208,
			cropId: 'crossroads',
			plane: 'base',
			textureKey: 'meadow-entry-crossroads-base',
			drawOrder: 200
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/crossroads-foreground.png',
			sha256: 'ce5656cd0a5b426b7d35742fc02a79f72aa83b262f5bee8a6264fe05f710a26d',
			bytes: 79432,
			width: 1600,
			height: 2208,
			cropId: 'crossroads',
			plane: 'foreground',
			textureKey: 'meadow-entry-crossroads-foreground',
			drawOrder: 200
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/tidewatch-coast-base.png',
			sha256: '9016d3a934da81a97e5fd61d9316ca0d93810d41990e7681d6ae17299f2e52c1',
			bytes: 15781759,
			width: 3744,
			height: 2080,
			cropId: 'tidewatch-coast',
			plane: 'base',
			textureKey: 'meadow-entry-tidewatch-coast-base',
			drawOrder: 210
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/tidewatch-coast-foreground.png',
			sha256: 'ea98407147254ccaeaa9a2a07449788f02a81bc19b95478373f4be8630445d82',
			bytes: 505712,
			width: 3744,
			height: 2080,
			cropId: 'tidewatch-coast',
			plane: 'foreground',
			textureKey: 'meadow-entry-tidewatch-coast-foreground',
			drawOrder: 210
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/mistfen-base.png',
			sha256: 'a8e0e7fc1c7d00d7a60f66a010de45e7f1808c0a2e7f2609687d5d5a6b96e8cd',
			bytes: 13465246,
			width: 2592,
			height: 2944,
			cropId: 'mistfen',
			plane: 'base',
			textureKey: 'meadow-entry-mistfen-base',
			drawOrder: 220
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/mistfen-foreground.png',
			sha256: 'f5db7ba6e9e7963a89b5557dc2d44233f28062849af694a5eee8aa55a6803280',
			bytes: 131276,
			width: 2592,
			height: 2944,
			cropId: 'mistfen',
			plane: 'foreground',
			textureKey: 'meadow-entry-mistfen-foreground',
			drawOrder: 220
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/silverpine-base.png',
			sha256: '41f94f45f999b2ee3dd575ae9386f63434c1b52d0491300bb47484133fcba92f',
			bytes: 12192835,
			width: 1888,
			height: 3008,
			cropId: 'silverpine',
			plane: 'base',
			textureKey: 'meadow-entry-silverpine-base',
			drawOrder: 230
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/silverpine-foreground.png',
			sha256: '0fbcb5d2e0dafc78b7f83e984079ddfdfcbcf77d85d4c37f2d9174a1fd2e3ca6',
			bytes: 379376,
			width: 1888,
			height: 3008,
			cropId: 'silverpine',
			plane: 'foreground',
			textureKey: 'meadow-entry-silverpine-foreground',
			drawOrder: 230
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/wildwood-base.png',
			sha256: '012c88fb4ceea5f06ffcc3b95901c48854449ca3b14223bc916fc2d1e07df08f',
			bytes: 24709139,
			width: 2688,
			height: 4928,
			cropId: 'wildwood',
			plane: 'base',
			textureKey: 'meadow-entry-wildwood-base',
			drawOrder: 240
		},
		{
			path: 'artifacts/meadow-entry/hpa-399/exports/wildwood-foreground.png',
			sha256: 'd1c24a3fbf99ce13aeeb280157dbb95661c545c3f9fd77b86d809ea490609932',
			bytes: 221277,
			width: 2688,
			height: 4928,
			cropId: 'wildwood',
			plane: 'foreground',
			textureKey: 'meadow-entry-wildwood-foreground',
			drawOrder: 240
		}
	],
	proofs: [
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/full/base-master.png',
			sha256: '9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
			bytes: 75418273,
			width: 6400,
			height: 6400,
			proofId: 'full/base-master',
			inputSha256: ['9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c']
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/full/foreground-checkerboard.png',
			sha256: '07960cdbcfabbdc37a74d37a4400e975d0ab65443ed520dfb6387fcadf665655',
			bytes: 1902519,
			width: 6400,
			height: 6400,
			proofId: 'full/foreground-checkerboard',
			inputSha256: ['c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e']
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/full/immutable-sundrop-composite.png',
			sha256: '058f9dde7fb0543d6f5731a8caa68411d5ac22d631a547305e0f62258fc9a9d1',
			bytes: 75514446,
			width: 6400,
			height: 6400,
			proofId: 'full/immutable-sundrop-composite',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/full/protected-live-overlay.png',
			sha256: '0ab18072a9b2789f62ff5fc0a607bdfc2637fab87d2c942d669c8ab2b70b0d89',
			bytes: 59062560,
			width: 6400,
			height: 6400,
			proofId: 'full/protected-live-overlay',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'1aed92216306a76936e9537276099c64d86096dbbf857b6fce073d35063db91b'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/full/collision-overlay.png',
			sha256: 'a0414883d044e7a0ac9cb00963b9b6d415999167ecbd09a30a6fcd298e12cee3',
			bytes: 60983127,
			width: 6400,
			height: 6400,
			proofId: 'full/collision-overlay',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'd879b61f98f966863db429fc4fdc40c58f868c0ed2877faeb33b147dd0b4c05a'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/full/foreground-eligibility-overlay.png',
			sha256: '99d3e53e86c28634f4d6ca2053539737891f48bb634f1f53a42feff2b78f1210',
			bytes: 3933003,
			width: 6400,
			height: 6400,
			proofId: 'full/foreground-eligibility-overlay',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'4a0e0bb19a91db5277ac1843f8672412fe5b931f602f9dd514686acd113fc5e1'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/full/interaction-readability-overlay.png',
			sha256: '4d4bbcbad95f8a3cdfd77bf5d58187d4106f532ac452aca8c5af4d9db19f5429',
			bytes: 55779751,
			width: 6400,
			height: 6400,
			proofId: 'full/interaction-readability-overlay',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'57a2acc0daea59ab06a97e5067389cc0bfc92334686b88d06df9df4704129b5c',
				'd667339707dfe3871fd9453f9d032465bdc518cadfdd8479606631f7c4c0ea62',
				'ce29ddfb25cc725507aa120bc71af9106dbd1fd2bca92f5d7db4e73d76dfd178'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/full/baked-coverage.png',
			sha256: 'bcdbec33847c2eb5d395224296ada5c5ed1cb4b70b7a4a310cc36658d804a385',
			bytes: 891010,
			width: 6400,
			height: 6400,
			proofId: 'full/baked-coverage',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'9e61df510372f658c28618c17c7318dc0ea5bfa5dbb91d189f7750e950929bde'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/full/fallback-coverage.png',
			sha256: '6eada03e806b9256a1ed485d7ab55088de33913f88d76c97b864c57f890f5359',
			bytes: 74869822,
			width: 6400,
			height: 6400,
			proofId: 'full/fallback-coverage',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'a4fc0b2c18969f0fdd32d64c1cf802194abc2b99058ede9e41fb6e6956c27f4c'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/regions/sundrop-village-underlay.png',
			sha256: '8367ce51ee8c216e66048eb8279e750962a4ba79a36a1136738ef40867c95115',
			bytes: 7497766,
			width: 1792,
			height: 1536,
			proofId: 'regions/sundrop-village-underlay',
			inputSha256: ['8367ce51ee8c216e66048eb8279e750962a4ba79a36a1136738ef40867c95115']
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/regions/outer-boundary-east-forest-lane.png',
			sha256: 'ddbc722719d67ee2e1101c7ebbccb3ab8a78e5374114a23067a99e498e74e2cc',
			bytes: 12196325,
			width: 1440,
			height: 4608,
			proofId: 'regions/outer-boundary-east-forest-lane',
			inputSha256: ['ddbc722719d67ee2e1101c7ebbccb3ab8a78e5374114a23067a99e498e74e2cc']
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/connectors/village-crossroads-connector.png',
			sha256: '6f2daf348295d7e6ce80c3437f845223dee1c0404ec5b9806cf1eef6dc43e6c2',
			bytes: 5746866,
			width: 1920,
			height: 1376,
			proofId: 'connectors/village-crossroads-connector',
			inputSha256: [
				'1875020048ae66971061ea5e1c4d69f8682c82a6e35c5ef75af1aed8a671dd6b',
				'21a1ee9d6c354d00782eb0583917dc92b07733ab3e2502da0b9e80934ed352ea'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/connectors/crossroads-coast-connector.png',
			sha256: 'a403a41ceb162423ed51f138b67d0d9245018d36121256c85269f1b82ed42a2f',
			bytes: 3061658,
			width: 1184,
			height: 1280,
			proofId: 'connectors/crossroads-coast-connector',
			inputSha256: [
				'7d7b5ccbd98c928eea4c5c464d849780db59b7b1e6902fd2b0e3ceea8453faac',
				'75743509b8120ee767c27723b8dfc04cd868c8050c09efab020100c65ffa3727'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/connectors/crossroads-mistfen-connector.png',
			sha256: 'b0957181ef17880e5cd0b334967b405ea71fc3a5f95bbe9a28c4ab356922aff4',
			bytes: 2846234,
			width: 1088,
			height: 1280,
			proofId: 'connectors/crossroads-mistfen-connector',
			inputSha256: [
				'564036dc1bf04b3af970664d114f8bb0f32072588f90ada73c9835aca608e9ab',
				'16a0775fc314561d6a99e1e8eff69f555ff415d2e7878fa4d7a793c894401c52'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/connectors/crossroads-silverpine-connector.png',
			sha256: 'ef1888719452750ec821a495be4662963d7969d95864464a9f19fb3e41eec317',
			bytes: 855157,
			width: 800,
			height: 480,
			proofId: 'connectors/crossroads-silverpine-connector',
			inputSha256: [
				'71cb8b34953b34f57c099c26b1a45961dbeff3ec60b7d07b795672d12f48702d',
				'2cf1cd7763691c40abc007801ea82f49969f87c504733002bc2469d496ef8542'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/connectors/crossroads-wildwood-connector.png',
			sha256: 'cc3a19f250a3c1ff8b28352baf77269856e448808a3a05fb92210ae407ae1faa',
			bytes: 1908430,
			width: 640,
			height: 1472,
			proofId: 'connectors/crossroads-wildwood-connector',
			inputSha256: [
				'c5be6d9e8ea6c9acefa82cac34caac5995aff51117d572ba0e95f94f068991c0',
				'3549f849229c20c892ac66f4f8247cf6d247f64a319d825923d2008e55572fa6'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/regions/crossroads.png',
			sha256: 'bb64b398283608a2af6e259d3d2034841fa22b223dc62554f1ea22a9c79788d6',
			bytes: 7590361,
			width: 1600,
			height: 2208,
			proofId: 'regions/crossroads',
			inputSha256: [
				'241671fd530810cc95ec20665eacd3f7080501691e912694f68f2a20963d0949',
				'ce5656cd0a5b426b7d35742fc02a79f72aa83b262f5bee8a6264fe05f710a26d'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/regions/tidewatch-coast.png',
			sha256: '2f9afc7cd4a9ef47a477776c3e0909a5a2a444148967d90075314e56949d5281',
			bytes: 15800555,
			width: 3744,
			height: 2080,
			proofId: 'regions/tidewatch-coast',
			inputSha256: [
				'9016d3a934da81a97e5fd61d9316ca0d93810d41990e7681d6ae17299f2e52c1',
				'ea98407147254ccaeaa9a2a07449788f02a81bc19b95478373f4be8630445d82'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/regions/mistfen.png',
			sha256: '93a21d24132692b7276eb949ee349859fdd14df0fbfee62b9e17f1ef25101b60',
			bytes: 13463050,
			width: 2592,
			height: 2944,
			proofId: 'regions/mistfen',
			inputSha256: [
				'a8e0e7fc1c7d00d7a60f66a010de45e7f1808c0a2e7f2609687d5d5a6b96e8cd',
				'f5db7ba6e9e7963a89b5557dc2d44233f28062849af694a5eee8aa55a6803280'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/regions/silverpine.png',
			sha256: '2ba5e14e4151438f855406604de697b9f008c1aca4056ec2fa3dc1f2fd1d1db5',
			bytes: 12186841,
			width: 1888,
			height: 3008,
			proofId: 'regions/silverpine',
			inputSha256: [
				'41f94f45f999b2ee3dd575ae9386f63434c1b52d0491300bb47484133fcba92f',
				'0fbcb5d2e0dafc78b7f83e984079ddfdfcbcf77d85d4c37f2d9174a1fd2e3ca6'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/regions/wildwood.png',
			sha256: '6dfd93366beb5e4bee85768901d5d3c93f14ba4414389244cd1001dc628d3366',
			bytes: 24728754,
			width: 2688,
			height: 4928,
			proofId: 'regions/wildwood',
			inputSha256: [
				'012c88fb4ceea5f06ffcc3b95901c48854449ca3b14223bc916fc2d1e07df08f',
				'd1c24a3fbf99ce13aeeb280157dbb95661c545c3f9fd77b86d809ea490609932'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-sundrop-village-underlay--village-crossroads-connector.png',
			sha256: '271930176c3fb52fb6e1616430012c9e4706371e645c3bed4fee1f9b778ee56d',
			bytes: 1906,
			width: 640,
			height: 736,
			proofId: 'overlaps/overlap-sundrop-village-underlay--village-crossroads-connector',
			inputSha256: [
				'8367ce51ee8c216e66048eb8279e750962a4ba79a36a1136738ef40867c95115',
				'1875020048ae66971061ea5e1c4d69f8682c82a6e35c5ef75af1aed8a671dd6b'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-outer-boundary-east-forest-lane--tidewatch-coast.png',
			sha256: '7c6545d0c57743b89695fff0a7b7d00b535a4967bebbc7f19af876d25c34f77d',
			bytes: 6702,
			width: 1440,
			height: 1184,
			proofId: 'overlaps/overlap-outer-boundary-east-forest-lane--tidewatch-coast',
			inputSha256: [
				'ddbc722719d67ee2e1101c7ebbccb3ab8a78e5374114a23067a99e498e74e2cc',
				'9016d3a934da81a97e5fd61d9316ca0d93810d41990e7681d6ae17299f2e52c1'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-outer-boundary-east-forest-lane--wildwood.png',
			sha256: '1bcdf1d1e24a1f27d53d91011d42da1b60ae87bc8f142a79735cb653a6d18363',
			bytes: 23389,
			width: 1440,
			height: 4160,
			proofId: 'overlaps/overlap-outer-boundary-east-forest-lane--wildwood',
			inputSha256: [
				'ddbc722719d67ee2e1101c7ebbccb3ab8a78e5374114a23067a99e498e74e2cc',
				'012c88fb4ceea5f06ffcc3b95901c48854449ca3b14223bc916fc2d1e07df08f'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-village-crossroads-connector--crossroads-coast-connector.png',
			sha256: 'cbdad4835cc95b06081c26f18e1e01f3cdfb8bc3e230c4c582feba24af1856b9',
			bytes: 163,
			width: 32,
			height: 672,
			proofId: 'overlaps/overlap-village-crossroads-connector--crossroads-coast-connector',
			inputSha256: [
				'1875020048ae66971061ea5e1c4d69f8682c82a6e35c5ef75af1aed8a671dd6b',
				'7d7b5ccbd98c928eea4c5c464d849780db59b7b1e6902fd2b0e3ceea8453faac',
				'21a1ee9d6c354d00782eb0583917dc92b07733ab3e2502da0b9e80934ed352ea',
				'75743509b8120ee767c27723b8dfc04cd868c8050c09efab020100c65ffa3727'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-village-crossroads-connector--crossroads.png',
			sha256: '287ae7d3ff23d70b2537d388bf0c5465cb38c42aea4226d8d68f7aac73636d33',
			bytes: 2172,
			width: 544,
			height: 992,
			proofId: 'overlaps/overlap-village-crossroads-connector--crossroads',
			inputSha256: [
				'1875020048ae66971061ea5e1c4d69f8682c82a6e35c5ef75af1aed8a671dd6b',
				'241671fd530810cc95ec20665eacd3f7080501691e912694f68f2a20963d0949',
				'21a1ee9d6c354d00782eb0583917dc92b07733ab3e2502da0b9e80934ed352ea',
				'ce5656cd0a5b426b7d35742fc02a79f72aa83b262f5bee8a6264fe05f710a26d'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-village-crossroads-connector--tidewatch-coast.png',
			sha256: 'e304288fe735fe4e3015fa58b62335b9c19c7ecf68e3b388208fdfe746d9f969',
			bytes: 2081,
			width: 672,
			height: 768,
			proofId: 'overlaps/overlap-village-crossroads-connector--tidewatch-coast',
			inputSha256: [
				'1875020048ae66971061ea5e1c4d69f8682c82a6e35c5ef75af1aed8a671dd6b',
				'9016d3a934da81a97e5fd61d9316ca0d93810d41990e7681d6ae17299f2e52c1',
				'21a1ee9d6c354d00782eb0583917dc92b07733ab3e2502da0b9e80934ed352ea',
				'ea98407147254ccaeaa9a2a07449788f02a81bc19b95478373f4be8630445d82'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-coast-connector--crossroads-wildwood-connector.png',
			sha256: 'd8d9fd4d6f6cb75decd36f370d70593f58072abd12c97d418a3f32d269e8abe5',
			bytes: 1668,
			width: 640,
			height: 640,
			proofId: 'overlaps/overlap-crossroads-coast-connector--crossroads-wildwood-connector',
			inputSha256: [
				'7d7b5ccbd98c928eea4c5c464d849780db59b7b1e6902fd2b0e3ceea8453faac',
				'c5be6d9e8ea6c9acefa82cac34caac5995aff51117d572ba0e95f94f068991c0',
				'75743509b8120ee767c27723b8dfc04cd868c8050c09efab020100c65ffa3727',
				'3549f849229c20c892ac66f4f8247cf6d247f64a319d825923d2008e55572fa6'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-coast-connector--crossroads.png',
			sha256: '48c08897bced47df5c34fa479cf8b2aaf5534f0249e1318fa60d02c28eb5dcd8',
			bytes: 1295,
			width: 1088,
			height: 288,
			proofId: 'overlaps/overlap-crossroads-coast-connector--crossroads',
			inputSha256: [
				'7d7b5ccbd98c928eea4c5c464d849780db59b7b1e6902fd2b0e3ceea8453faac',
				'241671fd530810cc95ec20665eacd3f7080501691e912694f68f2a20963d0949',
				'75743509b8120ee767c27723b8dfc04cd868c8050c09efab020100c65ffa3727',
				'ce5656cd0a5b426b7d35742fc02a79f72aa83b262f5bee8a6264fe05f710a26d'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-coast-connector--tidewatch-coast.png',
			sha256: '517e618727d3c4d53fbe4b8db6dee4376b24616c536cd1fe59943f851ea35cca',
			bytes: 5968,
			width: 1184,
			height: 1280,
			proofId: 'overlaps/overlap-crossroads-coast-connector--tidewatch-coast',
			inputSha256: [
				'7d7b5ccbd98c928eea4c5c464d849780db59b7b1e6902fd2b0e3ceea8453faac',
				'9016d3a934da81a97e5fd61d9316ca0d93810d41990e7681d6ae17299f2e52c1',
				'75743509b8120ee767c27723b8dfc04cd868c8050c09efab020100c65ffa3727',
				'ea98407147254ccaeaa9a2a07449788f02a81bc19b95478373f4be8630445d82'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-coast-connector--wildwood.png',
			sha256: 'c8debe2b57d85baa2ca09596dd98ba413710ee9ffe11630a11fce005260f7b58',
			bytes: 1985,
			width: 768,
			height: 640,
			proofId: 'overlaps/overlap-crossroads-coast-connector--wildwood',
			inputSha256: [
				'7d7b5ccbd98c928eea4c5c464d849780db59b7b1e6902fd2b0e3ceea8453faac',
				'012c88fb4ceea5f06ffcc3b95901c48854449ca3b14223bc916fc2d1e07df08f',
				'75743509b8120ee767c27723b8dfc04cd868c8050c09efab020100c65ffa3727',
				'd1c24a3fbf99ce13aeeb280157dbb95661c545c3f9fd77b86d809ea490609932'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-mistfen-connector--crossroads-silverpine-connector.png',
			sha256: '4385c9fbf394131d397fc7c013085ec49c59c22bdc9cc43340fbf547a5af286e',
			bytes: 735,
			width: 352,
			height: 480,
			proofId: 'overlaps/overlap-crossroads-mistfen-connector--crossroads-silverpine-connector',
			inputSha256: [
				'564036dc1bf04b3af970664d114f8bb0f32072588f90ada73c9835aca608e9ab',
				'71cb8b34953b34f57c099c26b1a45961dbeff3ec60b7d07b795672d12f48702d',
				'16a0775fc314561d6a99e1e8eff69f555ff415d2e7878fa4d7a793c894401c52',
				'2cf1cd7763691c40abc007801ea82f49969f87c504733002bc2469d496ef8542'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-mistfen-connector--crossroads.png',
			sha256: '6bc48ffad7f117a39dd3c080801e9c025333a5f8420bca833ee74e3ee98593c2',
			bytes: 2341,
			width: 480,
			height: 1216,
			proofId: 'overlaps/overlap-crossroads-mistfen-connector--crossroads',
			inputSha256: [
				'564036dc1bf04b3af970664d114f8bb0f32072588f90ada73c9835aca608e9ab',
				'241671fd530810cc95ec20665eacd3f7080501691e912694f68f2a20963d0949',
				'16a0775fc314561d6a99e1e8eff69f555ff415d2e7878fa4d7a793c894401c52',
				'ce5656cd0a5b426b7d35742fc02a79f72aa83b262f5bee8a6264fe05f710a26d'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-mistfen-connector--mistfen.png',
			sha256: 'b83bb0fe2db73b454f41c9314be8ff35102a6650624fcf62502c83486ce98f92',
			bytes: 1668,
			width: 512,
			height: 800,
			proofId: 'overlaps/overlap-crossroads-mistfen-connector--mistfen',
			inputSha256: [
				'564036dc1bf04b3af970664d114f8bb0f32072588f90ada73c9835aca608e9ab',
				'a8e0e7fc1c7d00d7a60f66a010de45e7f1808c0a2e7f2609687d5d5a6b96e8cd',
				'16a0775fc314561d6a99e1e8eff69f555ff415d2e7878fa4d7a793c894401c52',
				'f5db7ba6e9e7963a89b5557dc2d44233f28062849af694a5eee8aa55a6803280'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-mistfen-connector--silverpine.png',
			sha256: '258ef796f815e4c20d6a810c2deaa3231136a3bd3ba0e14c9d130221e0e4266b',
			bytes: 3048,
			width: 1088,
			height: 704,
			proofId: 'overlaps/overlap-crossroads-mistfen-connector--silverpine',
			inputSha256: [
				'564036dc1bf04b3af970664d114f8bb0f32072588f90ada73c9835aca608e9ab',
				'41f94f45f999b2ee3dd575ae9386f63434c1b52d0491300bb47484133fcba92f',
				'16a0775fc314561d6a99e1e8eff69f555ff415d2e7878fa4d7a793c894401c52',
				'0fbcb5d2e0dafc78b7f83e984079ddfdfcbcf77d85d4c37f2d9174a1fd2e3ca6'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-silverpine-connector--crossroads.png',
			sha256: '8a9f0010b2d745b63bf13cb534b39e042d0f2aae1d47f6274ac8b09febff6141',
			bytes: 1569,
			width: 800,
			height: 480,
			proofId: 'overlaps/overlap-crossroads-silverpine-connector--crossroads',
			inputSha256: [
				'71cb8b34953b34f57c099c26b1a45961dbeff3ec60b7d07b795672d12f48702d',
				'241671fd530810cc95ec20665eacd3f7080501691e912694f68f2a20963d0949',
				'2cf1cd7763691c40abc007801ea82f49969f87c504733002bc2469d496ef8542',
				'ce5656cd0a5b426b7d35742fc02a79f72aa83b262f5bee8a6264fe05f710a26d'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-silverpine-connector--silverpine.png',
			sha256: '9fc8e027f904e48b773dbe88c2f02f0652f5848d2b3f9431fc04df4bd3598a45',
			bytes: 1271,
			width: 800,
			height: 384,
			proofId: 'overlaps/overlap-crossroads-silverpine-connector--silverpine',
			inputSha256: [
				'71cb8b34953b34f57c099c26b1a45961dbeff3ec60b7d07b795672d12f48702d',
				'41f94f45f999b2ee3dd575ae9386f63434c1b52d0491300bb47484133fcba92f',
				'2cf1cd7763691c40abc007801ea82f49969f87c504733002bc2469d496ef8542',
				'0fbcb5d2e0dafc78b7f83e984079ddfdfcbcf77d85d4c37f2d9174a1fd2e3ca6'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-wildwood-connector--crossroads.png',
			sha256: '0a317f1e23b768e62d12d166141a5b6e6ace1f84c33707b5d7dc59375159b6ca',
			bytes: 2443,
			width: 544,
			height: 1120,
			proofId: 'overlaps/overlap-crossroads-wildwood-connector--crossroads',
			inputSha256: [
				'c5be6d9e8ea6c9acefa82cac34caac5995aff51117d572ba0e95f94f068991c0',
				'241671fd530810cc95ec20665eacd3f7080501691e912694f68f2a20963d0949',
				'3549f849229c20c892ac66f4f8247cf6d247f64a319d825923d2008e55572fa6',
				'ce5656cd0a5b426b7d35742fc02a79f72aa83b262f5bee8a6264fe05f710a26d'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-wildwood-connector--tidewatch-coast.png',
			sha256: '271930176c3fb52fb6e1616430012c9e4706371e645c3bed4fee1f9b778ee56d',
			bytes: 1906,
			width: 640,
			height: 736,
			proofId: 'overlaps/overlap-crossroads-wildwood-connector--tidewatch-coast',
			inputSha256: [
				'c5be6d9e8ea6c9acefa82cac34caac5995aff51117d572ba0e95f94f068991c0',
				'9016d3a934da81a97e5fd61d9316ca0d93810d41990e7681d6ae17299f2e52c1',
				'3549f849229c20c892ac66f4f8247cf6d247f64a319d825923d2008e55572fa6',
				'ea98407147254ccaeaa9a2a07449788f02a81bc19b95478373f4be8630445d82'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads-wildwood-connector--wildwood.png',
			sha256: 'e3fb45c8708fc9c4d196ed40dbd8ba27a8199ba268c018e047e660cdae599bee',
			bytes: 3733,
			width: 640,
			height: 1472,
			proofId: 'overlaps/overlap-crossroads-wildwood-connector--wildwood',
			inputSha256: [
				'c5be6d9e8ea6c9acefa82cac34caac5995aff51117d572ba0e95f94f068991c0',
				'012c88fb4ceea5f06ffcc3b95901c48854449ca3b14223bc916fc2d1e07df08f',
				'3549f849229c20c892ac66f4f8247cf6d247f64a319d825923d2008e55572fa6',
				'd1c24a3fbf99ce13aeeb280157dbb95661c545c3f9fd77b86d809ea490609932'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads--tidewatch-coast.png',
			sha256: '61480d3e7ee2daddaf964b320b9ec100172bc89b53cb6ff3c6aba73b4f4f17c0',
			bytes: 2461,
			width: 1600,
			height: 384,
			proofId: 'overlaps/overlap-crossroads--tidewatch-coast',
			inputSha256: [
				'241671fd530810cc95ec20665eacd3f7080501691e912694f68f2a20963d0949',
				'9016d3a934da81a97e5fd61d9316ca0d93810d41990e7681d6ae17299f2e52c1',
				'ce5656cd0a5b426b7d35742fc02a79f72aa83b262f5bee8a6264fe05f710a26d',
				'ea98407147254ccaeaa9a2a07449788f02a81bc19b95478373f4be8630445d82'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads--silverpine.png',
			sha256: '9abc4f756e5fe4376da14a70414aba8145736fe5d133feb388c4b826fcbe93aa',
			bytes: 2938,
			width: 1152,
			height: 640,
			proofId: 'overlaps/overlap-crossroads--silverpine',
			inputSha256: [
				'241671fd530810cc95ec20665eacd3f7080501691e912694f68f2a20963d0949',
				'41f94f45f999b2ee3dd575ae9386f63434c1b52d0491300bb47484133fcba92f',
				'ce5656cd0a5b426b7d35742fc02a79f72aa83b262f5bee8a6264fe05f710a26d',
				'0fbcb5d2e0dafc78b7f83e984079ddfdfcbcf77d85d4c37f2d9174a1fd2e3ca6'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-crossroads--wildwood.png',
			sha256: 'c821a6caea7397bb865f14baaa48f0d727dee27aad9c962caa0adcdf3a8b2726',
			bytes: 5845,
			width: 672,
			height: 2208,
			proofId: 'overlaps/overlap-crossroads--wildwood',
			inputSha256: [
				'241671fd530810cc95ec20665eacd3f7080501691e912694f68f2a20963d0949',
				'012c88fb4ceea5f06ffcc3b95901c48854449ca3b14223bc916fc2d1e07df08f',
				'ce5656cd0a5b426b7d35742fc02a79f72aa83b262f5bee8a6264fe05f710a26d',
				'd1c24a3fbf99ce13aeeb280157dbb95661c545c3f9fd77b86d809ea490609932'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-tidewatch-coast--wildwood.png',
			sha256: '0e860e530b35b7551043e418c799544df3a1edcfebbddb603ea86918436d3051',
			bytes: 7761,
			width: 2688,
			height: 736,
			proofId: 'overlaps/overlap-tidewatch-coast--wildwood',
			inputSha256: [
				'9016d3a934da81a97e5fd61d9316ca0d93810d41990e7681d6ae17299f2e52c1',
				'012c88fb4ceea5f06ffcc3b95901c48854449ca3b14223bc916fc2d1e07df08f',
				'ea98407147254ccaeaa9a2a07449788f02a81bc19b95478373f4be8630445d82',
				'd1c24a3fbf99ce13aeeb280157dbb95661c545c3f9fd77b86d809ea490609932'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-mistfen--silverpine.png',
			sha256: 'b5b14cf936ae1444d9fce3b50d268b82eb154c8f7512aead8515c0a5ec32bb2d',
			bytes: 7160,
			width: 640,
			height: 2848,
			proofId: 'overlaps/overlap-mistfen--silverpine',
			inputSha256: [
				'a8e0e7fc1c7d00d7a60f66a010de45e7f1808c0a2e7f2609687d5d5a6b96e8cd',
				'41f94f45f999b2ee3dd575ae9386f63434c1b52d0491300bb47484133fcba92f',
				'f5db7ba6e9e7963a89b5557dc2d44233f28062849af694a5eee8aa55a6803280',
				'0fbcb5d2e0dafc78b7f83e984079ddfdfcbcf77d85d4c37f2d9174a1fd2e3ca6'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/overlaps/overlap-silverpine--wildwood.png',
			sha256: '974b24176499bc28b0048889db1007c0c9c453061f887051245a835572bd715b',
			bytes: 2694,
			width: 224,
			height: 3008,
			proofId: 'overlaps/overlap-silverpine--wildwood',
			inputSha256: [
				'41f94f45f999b2ee3dd575ae9386f63434c1b52d0491300bb47484133fcba92f',
				'012c88fb4ceea5f06ffcc3b95901c48854449ca3b14223bc916fc2d1e07df08f',
				'0fbcb5d2e0dafc78b7f83e984079ddfdfcbcf77d85d4c37f2d9174a1fd2e3ca6',
				'd1c24a3fbf99ce13aeeb280157dbb95661c545c3f9fd77b86d809ea490609932'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/corners/corner-meadow-entry-handoff-network.png',
			sha256: 'ff59cc7ba984e5257aa1e5c7d992fd9ab75f1033426ec341433679b0a33a146c',
			bytes: 41332763,
			width: 4352,
			height: 5568,
			proofId: 'corners/corner-meadow-entry-handoff-network',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/clamps/tidewatch-coast-right.png',
			sha256: '315b911b15a1d9a234dfe18c5b4beb26560c2f8f4b509492017f13393072fe2c',
			bytes: 15786922,
			width: 3744,
			height: 2080,
			proofId: 'clamps/tidewatch-coast-right',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/clamps/tidewatch-coast-bottom.png',
			sha256: '722582b77f3a2be8eaa34f60348ed12e5668e59e253f9bdd6464291d5df7744a',
			bytes: 15771421,
			width: 3744,
			height: 2080,
			proofId: 'clamps/tidewatch-coast-bottom',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/clamps/wildwood-right.png',
			sha256: 'bfeb84b1f1de72cf07aebcd1b0ce16015449b50a089a09cdd4e7f5e8782f237f',
			bytes: 24696150,
			width: 2688,
			height: 4928,
			proofId: 'clamps/wildwood-right',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-000.png',
			sha256: '385c9a3b44774e93c9666932a68032073595539b0799843f6ce583d2931206c7',
			bytes: 25667,
			width: 6400,
			height: 128,
			proofId: 'fallback-boundaries/fallback-000',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-001.png',
			sha256: '8c2f99f04fce2c2c0f55f75d26ffc623a401c5ddfc04e1ba5e10eef024aa514c',
			bytes: 22256,
			width: 2048,
			height: 160,
			proofId: 'fallback-boundaries/fallback-001',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-005.png',
			sha256: '4a82208492e17b28c306ab5621fe412fcc03904fe36e54d4383330d35bf4052b',
			bytes: 5604,
			width: 96,
			height: 608,
			proofId: 'fallback-boundaries/fallback-005',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-011.png',
			sha256: '18efa447a5c7db4acaf9635cd4b192686fe4dc18ef2bfaacb285ecb7eb57267c',
			bytes: 8112,
			width: 96,
			height: 1536,
			proofId: 'fallback-boundaries/fallback-011',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-019.png',
			sha256: 'd294b96848ccc3de88e2071cbd64fa8ed3bda211961d09b823d7868ca0a5f0fa',
			bytes: 3856,
			width: 96,
			height: 64,
			proofId: 'fallback-boundaries/fallback-019',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-029.png',
			sha256: '7c1b9da5ccb71878623ee23f88933914680d504a3b7602aac3b0807317b60286',
			bytes: 4548,
			width: 96,
			height: 256,
			proofId: 'fallback-boundaries/fallback-029',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-041.png',
			sha256: '78022b7ecd4e50543d9dd5e29b31515a4f181a0d34c3fb9f061d0f9e2f5343ac',
			bytes: 4953,
			width: 96,
			height: 384,
			proofId: 'fallback-boundaries/fallback-041',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-054.png',
			sha256: 'c2c7a6d10cdfdf6ea209f723d784512121ed10d4184c6097b1ebae295fd96911',
			bytes: 3989,
			width: 96,
			height: 96,
			proofId: 'fallback-boundaries/fallback-054',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-065.png',
			sha256: 'cc42927c4174d58156c8bf6251881c0e6057c00b4bac212aceb8446ce32189b6',
			bytes: 50807,
			width: 2176,
			height: 352,
			proofId: 'fallback-boundaries/fallback-065',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-073.png',
			sha256: '65581640cd5e0f36781779052b5edc0b7d04ffb0eaf7626df71853e26dce7e2d',
			bytes: 17807,
			width: 2176,
			height: 128,
			proofId: 'fallback-boundaries/fallback-073',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-083.png',
			sha256: '091f6c09ce7d25e3d80af923c71de91707a3f906a788938b835abcef3411133c',
			bytes: 80708,
			width: 1408,
			height: 608,
			proofId: 'fallback-boundaries/fallback-083',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-093.png',
			sha256: '1ee2076c2ae422653277a4b29cfabadc9c39bbfe689198041659c18d03a91c55',
			bytes: 3280,
			width: 1408,
			height: 32,
			proofId: 'fallback-boundaries/fallback-093',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-104.png',
			sha256: '0a6c2684269e6eee5506c3e037460d6f3f0e5124b0aa888bcf0f7cbdc5f89957',
			bytes: 4632,
			width: 256,
			height: 64,
			proofId: 'fallback-boundaries/fallback-104',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-117.png',
			sha256: 'c8361eb9bc1da9ab89f75a7cee4055b864198e17958ffebd818fe6589b61e7ea',
			bytes: 9868,
			width: 256,
			height: 288,
			proofId: 'fallback-boundaries/fallback-117',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-131.png',
			sha256: '4ed454b981848db6c4b202d380d819d3ac820915ce897ea466f75763c091ff93',
			bytes: 11328,
			width: 256,
			height: 352,
			proofId: 'fallback-boundaries/fallback-131',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-143.png',
			sha256: 'a0559d057cef70942290c54e5efbd37f9f0d124420a91b45add391eb8a8c1ac5',
			bytes: 2524,
			width: 256,
			height: 32,
			proofId: 'fallback-boundaries/fallback-143',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-153.png',
			sha256: 'e81a285699cd53a200d61403f9bb0be05862010afb01a99e02a55b609bc06279',
			bytes: 12767,
			width: 256,
			height: 416,
			proofId: 'fallback-boundaries/fallback-153',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-155.png',
			sha256: 'd388afe191033621296f88e3bfa5c87106aa32bc0a15767ba5c92f63aa9c82fc',
			bytes: 47844,
			width: 608,
			height: 416,
			proofId: 'fallback-boundaries/fallback-155',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-161.png',
			sha256: '93d92c13170cc4befe5283d6cea38d49e58855361b2abe70b4ffecffe337d12d',
			bytes: 7661,
			width: 256,
			height: 192,
			proofId: 'fallback-boundaries/fallback-161',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-163.png',
			sha256: '8e60639f714d992da68127ba337590f501ee4eee4401c9a8b743f5e0fca38e28',
			bytes: 21571,
			width: 608,
			height: 192,
			proofId: 'fallback-boundaries/fallback-163',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-167.png',
			sha256: '93d92c13170cc4befe5283d6cea38d49e58855361b2abe70b4ffecffe337d12d',
			bytes: 7661,
			width: 256,
			height: 192,
			proofId: 'fallback-boundaries/fallback-167',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-169.png',
			sha256: '8e60639f714d992da68127ba337590f501ee4eee4401c9a8b743f5e0fca38e28',
			bytes: 21571,
			width: 608,
			height: 192,
			proofId: 'fallback-boundaries/fallback-169',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-171.png',
			sha256: '63d75e7f8a35e9584965dfcc7c331a29dca69521849879aba23a1f4db880b666',
			bytes: 60733,
			width: 2656,
			height: 398,
			proofId: 'fallback-boundaries/fallback-171',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-173.png',
			sha256: '95d4db20343017b161b15d0374ee55ed9547588881c05decb148ac06479d2c0b',
			bytes: 3750,
			width: 64,
			height: 50,
			proofId: 'fallback-boundaries/fallback-173',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-174.png',
			sha256: 'f12529002722df8c87e50b817418b5a1dc44c31ca3e3b3839ae903393413d182',
			bytes: 3756,
			width: 100,
			height: 50,
			proofId: 'fallback-boundaries/fallback-174',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-175.png',
			sha256: '8c83836f03a5f00a124565ed4139191329a6e42e4df6fe8a9f8b6085c3121206',
			bytes: 6602,
			width: 2492,
			height: 50,
			proofId: 'fallback-boundaries/fallback-175',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/fallback-boundaries/fallback-177.png',
			sha256: '1c0467dd41567c282c3c837dfb8f9baac2bab4b1080c7f43e288933f550d9088',
			bytes: 8921,
			width: 2656,
			height: 64,
			proofId: 'fallback-boundaries/fallback-177',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/sundrop-feather/top.png',
			sha256: '5fa1866a59491b54f9be2724414d357bce7e018fd1a25969e9074d7f4acecc76',
			bytes: 813602,
			width: 1792,
			height: 256,
			proofId: 'sundrop-feather/top',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/sundrop-feather/right.png',
			sha256: 'a310065ba32f2c59fdbb5870c003ce95be1b13dc6a3e54e211dcdd21267c1a55',
			bytes: 762159,
			width: 256,
			height: 1536,
			proofId: 'sundrop-feather/right',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/sundrop-feather/bottom.png',
			sha256: '36ff32b60dc3fddada64729e12121e2e44a8f0f51ee856fe877e11ec4bd9f3de',
			bytes: 649603,
			width: 1792,
			height: 256,
			proofId: 'sundrop-feather/bottom',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		},
		{
			path: 'docs/superpowers/reports/img/hpa-399/proofs/sundrop-feather/left.png',
			sha256: 'b7bb13eb81a43e47be06f719b3084e7adc59f3a51f3856df5067b244aa9f5a88',
			bytes: 583193,
			width: 256,
			height: 1536,
			proofId: 'sundrop-feather/left',
			inputSha256: [
				'9a5097eea014d092e57a8953be0dec2a16c1e6d29446f8b293338bf95a93752c',
				'f1184b045c27c544ac18937a4f8ccfa12cd386319b1722be5d808aea8048ade6',
				'c9ffa6e50a8e3c9f9888a642078094e95d9175158df8d262de8ac94b1ab9124e',
				'2d0a6703de1a404e49c0746f092a4c6f9f113ae17cd8bc35de635b5ec084ce45',
				'9a8b7ee79c37a507236de9bacf553af708bcd8292cb1d5949febbda71d7dc7ab'
			]
		}
	],
	evidencePath: 'docs/superpowers/reports/2026-07-30-hpa-399-visual-masters-exports-validation.md'
};
