/** Generated by tools/approve-meadow-entry-painted-v2-complete-art-package.ts. */
export const meadowEntryPaintedV2CompleteArtPackageApprovalReview = {
	reviewedBy: 'chanwaichan',
	reviewedAt: '2026-08-23T08:22:50Z'
} as const;

export const meadowEntryPaintedV2CompleteArtPackageApproval = {
	packageId: 'meadow-entry-painted-v2-complete',
	coverage: 'full-map',
	combinedControlFingerprint: '59ded996de5f7a468a7ef2d57219c851bf3d77488cfe8f3c9dedcbb3ea5c33b9',
	storageMode: 'git-lfs',
	storageConfigurationSha256: '42455c6bab7889dd99cc194683ccaa6f2a19b0a067aede17fe34faf6282fd1ab',
	master: {
		path: 'artifacts/meadow-entry/painted-v2/complete/masters/meadow-entry-painted-v2-complete-base-master.png',
		sha256: '11a417318b089b6cc1a47bee639306bb78379b7847ea42598c789b57c76c6a52',
		bytes: 121830680,
		width: 6400,
		height: 6400
	},
	masterProvenanceSha256: '6f14a08f43373a9afa98eb3e1cbc0bcd2655deea67947d453491dcfb45579352',
	exportProvenanceSha256: 'f0e87bad23824e2df38e8f6d2c43162f7f14559df06a13c5a78a462f4471d9e6',
	cropManifestSha256: '5e1cfc1957a72028b8f9e912892159b30517a1fa683ae82c0da02bc9a37c2870',
	textureProbe: {
		path: 'artifacts/meadow-entry/painted-v2/complete/proofs/texture-probe/browser-3200.json',
		sha256: 'feb3d7d0034338b06df69c3845925f4c868b820655267a3eab5154121d5c2c34'
	},
	reviewProofInventory: {
		path: 'docs/superpowers/reports/img/hpa-586-painted-v2-complete/complete-review-manifest.json',
		sha256: '8bec42cc6cf8b1e297413a9bba417f9beb97de6221f4e20f236d9f3ad2183f42'
	},
	validationReport: {
		path: 'docs/superpowers/reports/2026-08-22-meadow-entry-painted-v2-complete-validation.md',
		sha256: '6c05a3e71d119a82f696f8a660bfd77d979e1592c76d46d3a2b0ef946b25d806'
	},
	exports: [
		{
			path: 'public/game/assets/regions/meadow-entry-painted-v2/painted-v2-complete-northwest-base.png',
			sha256: 'd6e8c85f61071a1cb3927da36c78d36c30a1c45a7ed565074ea771781e77ac7d',
			bytes: 30274235,
			width: 3200,
			height: 3200,
			cropId: 'painted-v2-complete-northwest',
			plane: 'base',
			textureKey: 'meadow-entry-painted-v2-complete-northwest-base',
			drawOrder: 0
		},
		{
			path: 'public/game/assets/regions/meadow-entry-painted-v2/painted-v2-complete-northeast-base.png',
			sha256: '8bb684549f25792087da9a3a6511f704489123f83820afdde96b3ebfe00a3769',
			bytes: 29310427,
			width: 3200,
			height: 3200,
			cropId: 'painted-v2-complete-northeast',
			plane: 'base',
			textureKey: 'meadow-entry-painted-v2-complete-northeast-base',
			drawOrder: 10
		},
		{
			path: 'public/game/assets/regions/meadow-entry-painted-v2/painted-v2-complete-southwest-base.png',
			sha256: 'a3673e0f25eeb99927497cf4bdf47241602ff7ac86f4195ad46732444bb85dca',
			bytes: 30339781,
			width: 3200,
			height: 3200,
			cropId: 'painted-v2-complete-southwest',
			plane: 'base',
			textureKey: 'meadow-entry-painted-v2-complete-southwest-base',
			drawOrder: 20
		},
		{
			path: 'public/game/assets/regions/meadow-entry-painted-v2/painted-v2-complete-southeast-base.png',
			sha256: '9e67033819c20e000084c140a67ebab843fcf3855b938eb49da823ebb1b01c7b',
			bytes: 30546040,
			width: 3200,
			height: 3200,
			cropId: 'painted-v2-complete-southeast',
			plane: 'base',
			textureKey: 'meadow-entry-painted-v2-complete-southeast-base',
			drawOrder: 30
		}
	]
} as const;
