/** Generated by tools/approve-meadow-entry-controls.ts from reviewed checked-in controls. */
export interface MeadowEntryPaintedV2CompleteControlsApproval {
	combinedControlFingerprint: string;
	cropManifestSha256: string;
	bakeOwnershipSha256: string;
	storageMode: 'git-lfs';
	storageConfigurationSha256: string;
	evidencePath: 'docs/superpowers/reports/2026-08-19-complete-world-layout-foundation.md';
}

export const meadowEntryPaintedV2CompleteControlsApprovalReview = {
	reviewedBy: 'chanwaichan',
	reviewedAt: '2026-08-23T08:22:38Z'
} as const;

export const meadowEntryPaintedV2CompleteControlsApproval: MeadowEntryPaintedV2CompleteControlsApproval =
	{
	combinedControlFingerprint: '903877bef41cd4bf43e262177063a85d2301c8ec7f6d25d90329f41915ab952a',
	cropManifestSha256: '5e1cfc1957a72028b8f9e912892159b30517a1fa683ae82c0da02bc9a37c2870',
	bakeOwnershipSha256: 'a150543e3a185faeaf620878b8d6cf095686fa3208bca0d9739e29e4b0f11170',
	storageMode: 'git-lfs',
	storageConfigurationSha256: 'dacf4628cc52f936c7f10fb3e58c7e560e2094f9c847a8c46d598b94b08874ba',
	evidencePath: 'docs/superpowers/reports/2026-08-19-complete-world-layout-foundation.md'
};
