/** Generated by tools/approve-meadow-entry-controls.ts from reviewed checked-in controls. */
export interface MeadowEntryControlsApproval {
	combinedControlFingerprint: string;
	cropManifestSha256: string;
	bakeOwnershipSha256: string;
	storageMode: 'git-lfs';
	storageConfigurationSha256: string;
	evidencePath: 'docs/superpowers/reports/2026-08-12-meadow-entry-painted-camera-safe-controls.md';
}

export const meadowEntryControlsApprovalReview = {
	reviewedBy: 'chanwaichan',
	reviewedAt: '2026-08-17T00:19:53Z'
} as const;

export const meadowEntryControlsApproval: MeadowEntryControlsApproval = {
	combinedControlFingerprint: '1f55d4cda5549aeb082b80cd2e699be7d5f1d3d8acaaf4848704a5787f074e9a',
	cropManifestSha256: '639e5dc8862b6aa68ca115f6831454c884eb4b60965485274cbf12fadc49cade',
	bakeOwnershipSha256: 'bd9624b2b761e2071d9d45c1c556e71c05c3298cec8439db3220aa8eb2ed3e8e',
	storageMode: 'git-lfs',
	storageConfigurationSha256: '36737b6905cfc7c62fdf1bcdd48850bc574f20d7f4bfb63ab1aa8c727bc51de2',
	evidencePath: 'docs/superpowers/reports/2026-08-12-meadow-entry-painted-camera-safe-controls.md'
};
