/** Generated by tools/approve-meadow-entry-controls.ts from reviewed checked-in controls. */
export interface MeadowEntryControlsApproval {
	combinedControlFingerprint: string;
	cropManifestSha256: string;
	bakeOwnershipSha256: string;
	storageMode: 'git-lfs';
	storageConfigurationSha256: string;
	evidencePath: 'docs/superpowers/reports/2026-08-12-meadow-entry-painted-camera-safe-controls.md';
}

export const meadowEntryControlsApprovalReview = {
	reviewedBy: 'chanwaichan',
	reviewedAt: '2026-08-18T18:06:55Z'
} as const;

export const meadowEntryControlsApproval: MeadowEntryControlsApproval = {
	combinedControlFingerprint: 'a9de4332a3c5537f25d80eaeb2fcf1476ee97d76636f084bd9841da8055c96c7',
	cropManifestSha256: '639e5dc8862b6aa68ca115f6831454c884eb4b60965485274cbf12fadc49cade',
	bakeOwnershipSha256: '4978e4284862c8ce87c7193dadf23abca2033c36f5878035b01ca5951be85972',
	storageMode: 'git-lfs',
	storageConfigurationSha256: '42455c6bab7889dd99cc194683ccaa6f2a19b0a067aede17fe34faf6282fd1ab',
	evidencePath: 'docs/superpowers/reports/2026-08-12-meadow-entry-painted-camera-safe-controls.md'
};
