/** Generated by tools/approve-meadow-entry-controls.ts from reviewed checked-in controls. */
export interface MeadowEntryPaintedV2CompleteControlsApproval {
	combinedControlFingerprint: string;
	cropManifestSha256: string;
	bakeOwnershipSha256: string;
	storageMode: 'git-lfs';
	storageConfigurationSha256: string;
	evidencePath: 'docs/superpowers/reports/2026-08-19-complete-world-layout-foundation.md';
}

export const meadowEntryPaintedV2CompleteControlsApprovalReview = {
	reviewedBy: 'chanwaichan',
	reviewedAt: '2026-08-23T02:36:02Z'
} as const;

export const meadowEntryPaintedV2CompleteControlsApproval: MeadowEntryPaintedV2CompleteControlsApproval =
	{
		combinedControlFingerprint: '59ded996de5f7a468a7ef2d57219c851bf3d77488cfe8f3c9dedcbb3ea5c33b9',
		cropManifestSha256: '5e1cfc1957a72028b8f9e912892159b30517a1fa683ae82c0da02bc9a37c2870',
		bakeOwnershipSha256: '216922ba339a4290c7e6c12f7ce59f1ff1787a0c37dfcb44e9a4263dddb6c954',
		storageMode: 'git-lfs',
		storageConfigurationSha256: '46eb41c75bcc1d058c820f59098df48abccbaea1e081214d106d9d8ca6dd4f40',
		evidencePath: 'docs/superpowers/reports/2026-08-19-complete-world-layout-foundation.md'
	};
