import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import {
	collectStoryContentReferences,
	normalizeStoryContentReferences,
	renderStoryContentReferences,
	runStoryContentReferenceExporter,
	syncGeneratedStoryContentReferences,
	type StoryContentReferences
} from '../../../../tools/export-story-content-references';

const temporaryRoots: string[] = [];
const FIXTURE: StoryContentReferences = {
	mapIds: ['z-map', 'a-map'],
	npcIds: ['npc-z', 'npc-a'],
	questIds: ['quest-z', 'quest-a'],
	shopIds: ['shop-z', 'shop-a'],
	enemyIds: ['enemy-z', 'enemy-a'],
	npcPlacements: [
		['z-map', 'npc-z'],
		['a-map', 'npc-a']
	]
};

afterEach(() => {
	for (const root of temporaryRoots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe('story content reference generation', () => {
	it('renders sorted deterministic Rust with a generated header', () => {
		const source = renderStoryContentReferences(FIXTURE);
		expect(source).toMatch(
			/^\/\/ @generated by tools\/export-story-content-references\.ts\. Do not edit by hand\./
		);
		expect(source.indexOf('"a-map"')).toBeLessThan(source.indexOf('"z-map"'));
		expect(source.indexOf('("a-map", "npc-a")')).toBeLessThan(source.indexOf('("z-map", "npc-z")'));
		expect(source).toContain('pub const NPC_PLACEMENTS: &[(&str, &str)] = &[');
		expect(source.endsWith('\n')).toBe(true);
		expect(renderStoryContentReferences(FIXTURE)).toBe(source);
	});

	it('renders short ID lists in rustfmt-compatible form', () => {
		const source = renderStoryContentReferences(FIXTURE);
		expect(source).toContain('pub const SHOP_IDS: &[&str] = &["shop-a", "shop-z"];');
		expect(source).toContain('pub const ENEMY_IDS: &[&str] = &["enemy-a", "enemy-z"];');
	});

	it('escapes Rust string literals', () => {
		const source = renderStoryContentReferences({
			...FIXTURE,
			mapIds: ['map\\path'],
			npcIds: ['npc"quoted'],
			npcPlacements: [['map\\path', 'npc"quoted']]
		});
		expect(source).toContain('"map\\\\path"');
		expect(source).toContain('"npc\\"quoted"');
	});

	it('rejects duplicate IDs and placements', () => {
		expect(() => normalizeStoryContentReferences({ ...FIXTURE, mapIds: ['same', 'same'] })).toThrow(
			/duplicate map id same/
		);
		expect(() =>
			normalizeStoryContentReferences({
				...FIXTURE,
				npcPlacements: [
					['guild-hall', 'guild-master'],
					['guild-hall', 'guild-master']
				]
			})
		).toThrow(/duplicate npc placement guild-hall\/guild-master/);
	});

	it('checks exact bytes without writing missing or stale output', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-story-references-'));
		temporaryRoots.push(root);
		const destination = join(root, 'reference.rs');
		const source = renderStoryContentReferences(FIXTURE);

		expect(() => syncGeneratedStoryContentReferences(source, destination, true)).toThrow(
			/generated story references are missing/
		);
		writeFileSync(destination, 'stale\n');
		expect(() => syncGeneratedStoryContentReferences(source, destination, true)).toThrow(
			/generated story references are stale/
		);
		expect(readFileSync(destination, 'utf8')).toBe('stale\n');
	});

	it('publishes complete output and passes exact-byte check mode', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-story-references-'));
		temporaryRoots.push(root);
		const destination = join(root, 'nested', 'reference.rs');
		const source = renderStoryContentReferences(FIXTURE);

		syncGeneratedStoryContentReferences(source, destination, false);
		expect(readFileSync(destination, 'utf8')).toBe(source);
		expect(() => syncGeneratedStoryContentReferences(source, destination, true)).not.toThrow();
	});

	it('does not replace an existing destination when validation fails', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-story-references-'));
		temporaryRoots.push(root);
		const destination = join(root, 'reference.rs');
		writeFileSync(destination, 'previous\n');

		expect(() => renderStoryContentReferences({ ...FIXTURE, enemyIds: ['same', 'same'] })).toThrow(
			/duplicate enemy id same/
		);
		expect(readFileSync(destination, 'utf8')).toBe('previous\n');
	});

	it('collects the current authoritative registries', () => {
		const references = collectStoryContentReferences();
		expect(references.mapIds).toContain('guild-hall');
		expect(references.npcIds).toContain('guild-master');
		expect(references.questIds).toContain('investigate-the-ruins');
		expect(references.shopIds).toContain('miras-item-shop');
		expect(references.enemyIds).toContain('ruins-warden');
		expect(references.npcPlacements).toContainEqual(['guild-hall', 'guild-master']);
	});

	it('writes current references through the zero-argument CLI', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-story-references-'));
		temporaryRoots.push(root);
		const destination = join(root, 'src-tauri', 'src', 'story', 'reference.rs');

		runStoryContentReferenceExporter([], root);

		const output = readFileSync(destination, 'utf8');
		expect(output).toContain(
			'// @generated by tools/export-story-content-references.ts. Do not edit by hand.'
		);
		expect(output).toContain('("guild-hall", "guild-master")');
	});

	it('checks generated references through the check CLI mode', () => {
		const root = mkdtempSync(join(tmpdir(), 'gliese-story-references-'));
		temporaryRoots.push(root);

		runStoryContentReferenceExporter([], root);

		expect(() => runStoryContentReferenceExporter(['--check'], root)).not.toThrow();
	});

	it('rejects unexpected exporter arguments', () => {
		expect(() => runStoryContentReferenceExporter(['--write'])).toThrow(
			'Usage: bun tools/export-story-content-references.ts [--check]'
		);
	});
});
