use super::types::{
    NpcStoryDialogue, StoryBranchCondition, StoryCatalog, StoryDialogueAction, StoryDialogueBranch,
    StoryIntent,
};

pub fn generate_story_catalog_source(catalog: &StoryCatalog) -> String {
    let mut source = String::new();
    source.push_str("// @generated by story_check. Do not edit by hand.\n\n");
    source.push_str("use super::types::{\n");
    source.push_str(
        "    NpcStoryDialogue, StoryBranchCondition, StoryCatalog, StoryDialogueAction, StoryDialogueBranch,\n",
    );
    source.push_str("    StoryIntent,\n");
    source.push_str("};\n\n");
    source.push_str("pub fn story_catalog() -> StoryCatalog {\n");
    source.push_str("    StoryCatalog {\n");
    push_string_field(&mut source, 8, "package_id", &catalog.package_id);
    push_string_field(&mut source, 8, "default_locale", &catalog.default_locale);
    source.push_str("        npc_dialogues: vec![\n");

    for dialogue in &catalog.npc_dialogues {
        push_npc_dialogue(&mut source, dialogue, 12);
    }

    source.push_str("        ],\n");
    source.push_str("    }\n");
    source.push_str("}\n");
    source
}

fn push_npc_dialogue(source: &mut String, dialogue: &NpcStoryDialogue, indent: usize) {
    push_indent(source, indent);
    source.push_str("NpcStoryDialogue {\n");
    push_string_field(source, indent + 4, "npc_id", &dialogue.npc_id);
    push_indent(source, indent + 4);
    source.push_str("branches: vec![\n");

    for branch in &dialogue.branches {
        push_dialogue_branch(source, branch, indent + 8);
    }

    push_indent(source, indent + 4);
    source.push_str("],\n");
    push_indent(source, indent);
    source.push_str("},\n");
}

fn push_dialogue_branch(source: &mut String, branch: &StoryDialogueBranch, indent: usize) {
    push_indent(source, indent);
    source.push_str("StoryDialogueBranch {\n");
    push_indent(source, indent + 4);
    source.push_str("condition: ");
    source.push_str(branch_condition_source(branch.condition));
    source.push_str(",\n");
    push_string_field(source, indent + 4, "speaker", &branch.speaker);
    push_indent(source, indent + 4);
    source.push_str("lines: vec![\n");
    for line in &branch.lines {
        push_indent(source, indent + 8);
        push_rust_string(source, line);
        source.push_str(".to_string(),\n");
    }
    push_indent(source, indent + 4);
    source.push_str("],\n");
    push_indent(source, indent + 4);
    source.push_str("actions: vec![\n");
    for action in &branch.actions {
        push_dialogue_action(source, action, indent + 8);
    }
    push_indent(source, indent + 4);
    source.push_str("],\n");
    push_indent(source, indent + 4);
    source.push_str("completion_intent: ");
    match &branch.completion_intent {
        Some(intent) => {
            source.push_str("Some(");
            push_story_intent(source, intent, indent + 4);
            source.push(')');
        }
        None => source.push_str("None"),
    }
    source.push_str(",\n");
    push_indent(source, indent);
    source.push_str("},\n");
}

fn push_dialogue_action(source: &mut String, action: &StoryDialogueAction, indent: usize) {
    push_indent(source, indent);
    source.push_str("StoryDialogueAction {\n");
    push_string_field(source, indent + 4, "id", &action.id);
    push_string_field(source, indent + 4, "label", &action.label);
    push_indent(source, indent + 4);
    source.push_str("intent: ");
    push_story_intent(source, &action.intent, indent + 4);
    source.push_str(",\n");
    push_indent(source, indent);
    source.push_str("},\n");
}

fn push_story_intent(source: &mut String, intent: &StoryIntent, indent: usize) {
    match intent {
        StoryIntent::ShowQuestList { giver_npc_id } => {
            source.push_str("StoryIntent::ShowQuestList {\n");
            push_indent(source, indent + 4);
            source.push_str("giver_npc_id: ");
            push_rust_string(source, giver_npc_id);
            source.push_str(".to_string(),\n");
            push_indent(source, indent);
            source.push('}');
        }
        StoryIntent::OpenShop { shop_id } => {
            source.push_str("StoryIntent::OpenShop {\n");
            push_indent(source, indent + 4);
            source.push_str("shop_id: ");
            push_rust_string(source, shop_id);
            source.push_str(".to_string(),\n");
            push_indent(source, indent);
            source.push('}');
        }
        StoryIntent::RecordNpcTalk { npc_id } => {
            source.push_str("StoryIntent::RecordNpcTalk {\n");
            push_indent(source, indent + 4);
            source.push_str("npc_id: ");
            push_rust_string(source, npc_id);
            source.push_str(".to_string(),\n");
            push_indent(source, indent);
            source.push('}');
        }
        StoryIntent::Close => source.push_str("StoryIntent::Close"),
    }
}

fn branch_condition_source(condition: StoryBranchCondition) -> &'static str {
    match condition {
        StoryBranchCondition::Always => "StoryBranchCondition::Always",
        StoryBranchCondition::MainQuestNeedsGuildBriefing => {
            "StoryBranchCondition::MainQuestNeedsGuildBriefing"
        }
        StoryBranchCondition::GuildBriefingComplete => {
            "StoryBranchCondition::GuildBriefingComplete"
        }
        StoryBranchCondition::HasActiveSideQuest => "StoryBranchCondition::HasActiveSideQuest",
        StoryBranchCondition::HasCompletedQuest => "StoryBranchCondition::HasCompletedQuest",
    }
}

fn push_string_field(source: &mut String, indent: usize, field: &str, value: &str) {
    push_indent(source, indent);
    source.push_str(field);
    source.push_str(": ");
    push_rust_string(source, value);
    source.push_str(".to_string(),\n");
}

fn push_rust_string(source: &mut String, value: &str) {
    source.push('"');
    for character in value.chars() {
        match character {
            '\\' => source.push_str("\\\\"),
            '"' => source.push_str("\\\""),
            '\n' => source.push_str("\\n"),
            '\r' => source.push_str("\\r"),
            '\t' => source.push_str("\\t"),
            _ => source.push(character),
        }
    }
    source.push('"');
}

fn push_indent(source: &mut String, indent: usize) {
    for _ in 0..indent {
        source.push(' ');
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emits_current_rust_field_names_for_intent_payloads() {
        let catalog = StoryCatalog {
            package_id: "sundrop-ruins".to_string(),
            default_locale: "en".to_string(),
            npc_dialogues: vec![NpcStoryDialogue {
                npc_id: "guild-master".to_string(),
                branches: vec![StoryDialogueBranch {
                    condition: StoryBranchCondition::Always,
                    speaker: "Guild Master".to_string(),
                    lines: vec!["Ready?".to_string()],
                    actions: vec![
                        StoryDialogueAction {
                            id: "quest".to_string(),
                            label: "Quest".to_string(),
                            intent: StoryIntent::ShowQuestList {
                                giver_npc_id: "guild-master".to_string(),
                            },
                        },
                        StoryDialogueAction {
                            id: "shop".to_string(),
                            label: "Shop".to_string(),
                            intent: StoryIntent::OpenShop {
                                shop_id: "guild-quartermaster".to_string(),
                            },
                        },
                    ],
                    completion_intent: Some(StoryIntent::RecordNpcTalk {
                        npc_id: "guild-master".to_string(),
                    }),
                }],
            }],
        };

        let source = generate_story_catalog_source(&catalog);

        assert!(source.contains("// @generated by story_check. Do not edit by hand."));
        assert!(source.contains("giver_npc_id: \"guild-master\".to_string(),"));
        assert!(source.contains("shop_id: \"guild-quartermaster\".to_string(),"));
        assert!(source.contains("npc_id: \"guild-master\".to_string(),"));
        assert!(!source.contains("giverNpcId"));
        assert!(!source.contains("shopId"));
        assert!(!source.contains("npcId"));
    }
}
