// @generated by story_check. Do not edit by hand.

use super::types::{
    NpcStoryDialogue, StoryBranchCondition, StoryCatalog, StoryDialogueAction, StoryDialogueBranch,
    StoryIntent,
};

pub fn story_catalog() -> StoryCatalog {
    StoryCatalog {
        package_id: "sundrop-ruins".to_string(),
        default_locale: "en".to_string(),
        npc_dialogues: vec![
            NpcStoryDialogue {
                npc_id: "guild-master".to_string(),
                branches: vec![
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::MainQuestNeedsGuildBriefing,
                        speaker: "Guild Master Arlen".to_string(),
                        lines: vec![
                            "You made it. The eastern ruins are stirring again, and the village road is no longer safe.".to_string(),
                            "Go through the forest path, reach the old core, and defeat the warden before it wakes the rest.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "quest".to_string(),
                                label: "Quest".to_string(),
                                intent: StoryIntent::ShowQuestList {
                                    giver_npc_id: "guild-master".to_string(),
                                },
                            },
                        ],
                        completion_intent: Some(StoryIntent::RecordNpcTalk {
                            npc_id: "guild-master".to_string(),
                        }),
                    },
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::HasActiveSideQuest,
                        speaker: "Guild Master Arlen".to_string(),
                        lines: vec![
                            "The Guild board is yours to work through, but do not lose sight of the warden.".to_string(),
                            "Report progress through your journal. I will keep new work here at the counter.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "quest".to_string(),
                                label: "Quest".to_string(),
                                intent: StoryIntent::ShowQuestList {
                                    giver_npc_id: "guild-master".to_string(),
                                },
                            },
                        ],
                        completion_intent: None,
                    },
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::HasCompletedQuest,
                        speaker: "Guild Master Arlen".to_string(),
                        lines: vec![
                            "Good work out there. The village notices when a hunter keeps the roads clear.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "quest".to_string(),
                                label: "Quest".to_string(),
                                intent: StoryIntent::ShowQuestList {
                                    giver_npc_id: "guild-master".to_string(),
                                },
                            },
                        ],
                        completion_intent: None,
                    },
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::GuildBriefingComplete,
                        speaker: "Guild Master Arlen".to_string(),
                        lines: vec![
                            "The ruins route is open. Steel yourself before you enter the core.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "quest".to_string(),
                                label: "Quest".to_string(),
                                intent: StoryIntent::ShowQuestList {
                                    giver_npc_id: "guild-master".to_string(),
                                },
                            },
                        ],
                        completion_intent: None,
                    },
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::Always,
                        speaker: "Guild Master Arlen".to_string(),
                        lines: vec![
                            "The Guild keeps watch over the old road. Speak plainly and choose your work.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "quest".to_string(),
                                label: "Quest".to_string(),
                                intent: StoryIntent::ShowQuestList {
                                    giver_npc_id: "guild-master".to_string(),
                                },
                            },
                        ],
                        completion_intent: None,
                    },
                ],
            },
            NpcStoryDialogue {
                npc_id: "guild-quartermaster".to_string(),
                branches: vec![
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::GuildBriefingComplete,
                        speaker: "Quartermaster Vale".to_string(),
                        lines: vec![
                            "If you are bound for the ruins, buy what keeps you standing.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "shop".to_string(),
                                label: "Shop".to_string(),
                                intent: StoryIntent::OpenShop {
                                    shop_id: "guild-quartermaster".to_string(),
                                },
                            },
                        ],
                        completion_intent: None,
                    },
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::Always,
                        speaker: "Quartermaster Vale".to_string(),
                        lines: vec![
                            "Need field gear before the ruins? Guild stock is limited, but sturdy.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "shop".to_string(),
                                label: "Shop".to_string(),
                                intent: StoryIntent::OpenShop {
                                    shop_id: "guild-quartermaster".to_string(),
                                },
                            },
                        ],
                        completion_intent: None,
                    },
                ],
            },
            NpcStoryDialogue {
                npc_id: "shopkeeper-mira".to_string(),
                branches: vec![
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::GuildBriefingComplete,
                        speaker: "Mira".to_string(),
                        lines: vec![
                            "Back from the Guild? Take a tonic before the forest path gets rough.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "shop".to_string(),
                                label: "Shop".to_string(),
                                intent: StoryIntent::OpenShop {
                                    shop_id: "miras-item-shop".to_string(),
                                },
                            },
                        ],
                        completion_intent: None,
                    },
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::Always,
                        speaker: "Mira".to_string(),
                        lines: vec![
                            "Fresh tonics are on the shelf. The guild already stocked your field kit today.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "shop".to_string(),
                                label: "Shop".to_string(),
                                intent: StoryIntent::OpenShop {
                                    shop_id: "miras-item-shop".to_string(),
                                },
                            },
                        ],
                        completion_intent: None,
                    },
                ],
            },
            NpcStoryDialogue {
                npc_id: "villager-io".to_string(),
                branches: vec![
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::Always,
                        speaker: "Io".to_string(),
                        lines: vec![
                            "Old records say the ruins quiet down when someone brave reaches the core.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "close".to_string(),
                                label: "Close".to_string(),
                                intent: StoryIntent::Close,
                            },
                        ],
                        completion_intent: None,
                    },
                ],
            },
            NpcStoryDialogue {
                npc_id: "villager-lynn".to_string(),
                branches: vec![
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::Always,
                        speaker: "Lynn".to_string(),
                        lines: vec![
                            "The kettle is warm if you need a quiet minute before the road.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "close".to_string(),
                                label: "Close".to_string(),
                                intent: StoryIntent::Close,
                            },
                        ],
                        completion_intent: None,
                    },
                ],
            },
            NpcStoryDialogue {
                npc_id: "villager-toma".to_string(),
                branches: vec![
                    StoryDialogueBranch {
                        condition: StoryBranchCondition::Always,
                        speaker: "Toma".to_string(),
                        lines: vec![
                            "I patched the south fence this morning. If the slimes cross it again, tell the Guild.".to_string(),
                        ],
                        actions: vec![
                            StoryDialogueAction {
                                id: "close".to_string(),
                                label: "Close".to_string(),
                                intent: StoryIntent::Close,
                            },
                        ],
                        completion_intent: None,
                    },
                ],
            },
        ],
    }
}
