// @generated by tools/export-story-content-references.ts. Do not edit by hand.

pub const MAP_IDS: &[&str] = &[
    "guild-hall",
    "hero-house",
    "item-shop",
    "meadow-entry",
    "ruins-core",
    "ruins-threshold",
    "shrine-of-aurora-interior",
    "villager-house-1",
    "villager-house-2",
    "villager-house-3",
];

pub const NPC_IDS: &[&str] = &[
    "guild-master",
    "guild-quartermaster",
    "shopkeeper-mira",
    "villager-io",
    "villager-lynn",
    "villager-toma",
];

pub const QUEST_IDS: &[&str] = &[
    "investigate-the-ruins",
    "recover-ruins-relics",
    "thin-ruins-slimes",
    "thin-village-slimes",
];

pub const SHOP_IDS: &[&str] = &["guild-quartermaster", "miras-item-shop"];

pub const ENEMY_IDS: &[&str] = &["ruins-warden", "slime-scout"];

pub const NPC_PLACEMENTS: &[(&str, &str)] = &[
    ("guild-hall", "guild-master"),
    ("guild-hall", "guild-quartermaster"),
    ("item-shop", "shopkeeper-mira"),
    ("villager-house-1", "villager-lynn"),
    ("villager-house-2", "villager-toma"),
    ("villager-house-3", "villager-io"),
];
