import {
	existsSync,
	mkdirSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	renameSync,
	rmSync,
	writeFileSync
} from 'node:fs';
import { basename, dirname, join, relative, resolve } from 'node:path';

import {
	buildMeadowEntryControlInputs,
	computeMeadowEntryAuthoringContractFingerprint,
	computeMeadowEntryCombinedControlFingerprint,
	computeMeadowEntryGameplaySourceFingerprint,
	MEADOW_ENTRY_CONTROL_FILENAMES,
	renderMeadowEntryControls,
	type MeadowEntryControlPackage
} from '../src/lib/game/content/backgrounds/meadow-entry-controls';

export interface MeadowEntryExportPackage {
	readonly rendered: Readonly<Record<string, string>>;
	readonly generatedContents: string;
}

export interface MeadowEntryExportPaths {
	readonly repositoryRoot: string;
	readonly packageName?: MeadowEntryControlPackage;
	readonly controlsDirectory: string;
	readonly generatedPath: string;
}

export interface MeadowEntryExportFileSystem {
	existsSync: typeof existsSync;
	mkdirSync: typeof mkdirSync;
	mkdtempSync: typeof mkdtempSync;
	readdirSync: typeof readdirSync;
	readFileSync: typeof readFileSync;
	renameSync: typeof renameSync;
	rmSync: typeof rmSync;
	writeFileSync: typeof writeFileSync;
}

const NODE_FILE_SYSTEM: MeadowEntryExportFileSystem = {
	existsSync,
	mkdirSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	renameSync,
	rmSync,
	writeFileSync
};
const allowedControlFilenames = new Set<string>(MEADOW_ENTRY_CONTROL_FILENAMES);

interface MeadowEntryExportArguments {
	readonly packageName: MeadowEntryControlPackage;
	readonly checkMode: boolean;
}

function parseExportArguments(args: readonly string[]): MeadowEntryExportArguments {
	let packageName: MeadowEntryControlPackage = 'legacy';
	let checkMode = false;
	for (let index = args[0] === '--' ? 1 : 0; index < args.length; index += 1) {
		const flag = args[index];
		if (flag === '--check' && !checkMode) {
			checkMode = true;
			continue;
		}
		if (flag === '--package' && packageName === 'legacy') {
			const value = args[index + 1];
			if (value !== 'legacy' && value !== 'complete') {
				throw new Error(
					`Usage: bun tools/export-meadow-entry-art-controls.ts [--package legacy|complete] [--check]`
				);
			}
			packageName = value;
			index += 1;
			continue;
		}
		throw new Error(
			`Usage: bun tools/export-meadow-entry-art-controls.ts [--package legacy|complete] [--check]`
		);
	}
	return { packageName, checkMode };
}

export function meadowEntryExportPaths(
	repositoryRoot: string,
	packageName: MeadowEntryControlPackage = 'legacy'
): MeadowEntryExportPaths {
	if (packageName !== 'legacy' && packageName !== 'complete') {
		throw new Error(`Unknown meadow-entry control package "${packageName}"`);
	}
	const resolvedRoot = resolve(repositoryRoot);
	const packageRoot =
		packageName === 'complete'
			? 'artifacts/meadow-entry/painted-v2/complete'
			: 'artifacts/meadow-entry/painted-v2';
	const generatedName =
		packageName === 'complete'
			? 'meadow-entry-painted-v2-complete-art-control.ts'
			: 'meadow-entry-painted-v2-art-control.ts';
	return {
		repositoryRoot: resolvedRoot,
		packageName,
		controlsDirectory: resolve(resolvedRoot, packageRoot, 'controls'),
		generatedPath: resolve(resolvedRoot, 'src/lib/game/content/generated', generatedName)
	};
}

export function assertAllowedMeadowEntryDestination(
	paths: MeadowEntryExportPaths,
	path: string
): void {
	const relativePath = relative(paths.repositoryRoot, path).replaceAll('\\', '/');
	const controlsRelativePath = relative(paths.repositoryRoot, paths.controlsDirectory).replaceAll(
		'\\',
		'/'
	);
	const generatedRelativePath = relative(paths.repositoryRoot, paths.generatedPath).replaceAll(
		'\\',
		'/'
	);
	const allowed =
		relativePath === generatedRelativePath ||
		(relativePath.startsWith(`${controlsRelativePath}/`) &&
			allowedControlFilenames.has(relativePath.slice(`${controlsRelativePath}/`.length)));
	if (!allowed || relativePath.includes('/hpa-307/') || relativePath.includes('/hpa-398/')) {
		throw new Error(`Refusing unexpected meadow-entry control destination: ${relativePath}`);
	}
}

function generatedModule(
	gameplaySourceFingerprint: string,
	authoringContractFingerprint: string,
	combinedControlFingerprint: string
): string {
	return `/** @generated by tools/export-meadow-entry-art-controls.ts */
export const MEADOW_ENTRY_GAMEPLAY_SOURCE_FINGERPRINT =
\t'${gameplaySourceFingerprint}';
export const MEADOW_ENTRY_AUTHORING_CONTRACT_FINGERPRINT =
\t'${authoringContractFingerprint}';
export const MEADOW_ENTRY_COMBINED_CONTROL_FINGERPRINT =
\t'${combinedControlFingerprint}';
`;
}

function buildExportPackage(
	repositoryRoot: string,
	packageName: MeadowEntryControlPackage
): {
	packageBytes: MeadowEntryExportPackage;
	combinedControlFingerprint: string;
} {
	const inputs = buildMeadowEntryControlInputs(repositoryRoot, packageName);
	const rendered = renderMeadowEntryControls(inputs);
	const gameplaySourceFingerprint = computeMeadowEntryGameplaySourceFingerprint(inputs);
	const authoringContractFingerprint = computeMeadowEntryAuthoringContractFingerprint(inputs);
	const combinedControlFingerprint = computeMeadowEntryCombinedControlFingerprint(inputs);
	return {
		packageBytes: {
			rendered,
			generatedContents: generatedModule(
				gameplaySourceFingerprint,
				authoringContractFingerprint,
				combinedControlFingerprint
			)
		},
		combinedControlFingerprint
	};
}

function assertRenderedInventory(
	packageBytes: MeadowEntryExportPackage,
	paths: MeadowEntryExportPaths
): void {
	const actual = Object.keys(packageBytes.rendered);
	if (
		actual.length !== MEADOW_ENTRY_CONTROL_FILENAMES.length ||
		actual.some((filename, index) => filename !== MEADOW_ENTRY_CONTROL_FILENAMES[index])
	) {
		throw new Error(
			`Rendered meadow-entry control inventory drifted: ${actual.join(', ') || '(empty)'}`
		);
	}
	for (const filename of actual) {
		if (filename !== basename(filename) || filename.includes('..')) {
			throw new Error(`Refusing nested meadow-entry control path: ${filename}`);
		}
		assertAllowedMeadowEntryDestination(paths, join(paths.controlsDirectory, filename));
	}
	assertAllowedMeadowEntryDestination(paths, paths.generatedPath);
}

function checkedInControlFilenames(
	paths: MeadowEntryExportPaths,
	fileSystem: MeadowEntryExportFileSystem
): readonly string[] {
	if (!fileSystem.existsSync(paths.controlsDirectory)) return [];
	return fileSystem
		.readdirSync(paths.controlsDirectory, { withFileTypes: true })
		.map((entry) => {
			if (!entry.isFile()) {
				throw new Error(`Unexpected non-file in meadow-entry control inventory: ${entry.name}`);
			}
			return entry.name;
		})
		.sort();
}

function assertCheckedInControlInventory(
	paths: MeadowEntryExportPaths,
	fileSystem: MeadowEntryExportFileSystem,
	requireComplete: boolean
): void {
	const expected = [...MEADOW_ENTRY_CONTROL_FILENAMES].sort();
	const actual = checkedInControlFilenames(paths, fileSystem);
	const unexpected = actual.filter((filename) => !allowedControlFilenames.has(filename));
	const incomplete =
		requireComplete &&
		(actual.length !== expected.length ||
			actual.some((filename, index) => filename !== expected[index]));
	if (unexpected.length > 0 || incomplete) {
		throw new Error(
			`Checked-in meadow-entry control inventory differs from the fixed allowlist: expected [${expected.join(', ')}], received [${actual.join(', ')}]`
		);
	}
}

export function checkMeadowEntryExportPackage(
	packageBytes: MeadowEntryExportPackage,
	paths: MeadowEntryExportPaths,
	fileSystem: MeadowEntryExportFileSystem = NODE_FILE_SYSTEM
): void {
	assertRenderedInventory(packageBytes, paths);
	assertCheckedInControlInventory(paths, fileSystem, true);
	for (const filename of MEADOW_ENTRY_CONTROL_FILENAMES) {
		const path = join(paths.controlsDirectory, filename);
		assertAllowedMeadowEntryDestination(paths, path);
		const actual = fileSystem.readFileSync(path);
		const expected = Buffer.from(packageBytes.rendered[filename] ?? '', 'utf8');
		if (!actual.equals(expected)) {
			throw new Error(
				`Generated meadow-entry control is stale: ${relative(paths.repositoryRoot, path)}`
			);
		}
	}
	assertAllowedMeadowEntryDestination(paths, paths.generatedPath);
	if (
		!fileSystem.existsSync(paths.generatedPath) ||
		fileSystem.readFileSync(paths.generatedPath, 'utf8') !== packageBytes.generatedContents
	) {
		throw new Error(
			`Generated meadow-entry fingerprint module is stale: ${relative(paths.repositoryRoot, paths.generatedPath)}`
		);
	}
}

function restorePreviousPackage(
	paths: MeadowEntryExportPaths,
	fileSystem: MeadowEntryExportFileSystem,
	backupDirectory: string,
	state: {
		controlsBackedUp: boolean;
		generatedBackedUp: boolean;
		controlsPublished: boolean;
		generatedPublished: boolean;
	}
): void {
	if (state.controlsPublished && fileSystem.existsSync(paths.controlsDirectory)) {
		fileSystem.rmSync(paths.controlsDirectory, { recursive: true });
	}
	if (state.generatedPublished && fileSystem.existsSync(paths.generatedPath)) {
		fileSystem.rmSync(paths.generatedPath);
	}
	if (state.controlsBackedUp) {
		fileSystem.renameSync(join(backupDirectory, 'controls'), paths.controlsDirectory);
	}
	if (state.generatedBackedUp) {
		fileSystem.renameSync(join(backupDirectory, 'generated.ts'), paths.generatedPath);
	}
}

export function publishMeadowEntryExportPackage(
	packageBytes: MeadowEntryExportPackage,
	paths: MeadowEntryExportPaths,
	fileSystem: MeadowEntryExportFileSystem = NODE_FILE_SYSTEM
): void {
	assertRenderedInventory(packageBytes, paths);
	const controlsParent = dirname(paths.controlsDirectory);
	const generatedParent = dirname(paths.generatedPath);
	fileSystem.mkdirSync(controlsParent, { recursive: true });
	fileSystem.mkdirSync(generatedParent, { recursive: true });

	const hadControls = fileSystem.existsSync(paths.controlsDirectory);
	const hadGenerated = fileSystem.existsSync(paths.generatedPath);
	if (hadControls) assertCheckedInControlInventory(paths, fileSystem, false);

	const temporaryControls = fileSystem.mkdtempSync(
		join(controlsParent, '.meadow-entry-package-controls-')
	);
	const temporaryGeneratedDirectory = fileSystem.mkdtempSync(
		join(generatedParent, '.meadow-entry-package-generated-')
	);
	const temporaryGenerated = join(temporaryGeneratedDirectory, 'generated.ts');
	const backupDirectory = fileSystem.mkdtempSync(
		join(controlsParent, '.meadow-entry-package-backup-')
	);
	let packagePublished = false;
	const state = {
		controlsBackedUp: false,
		generatedBackedUp: false,
		controlsPublished: false,
		generatedPublished: false
	};
	try {
		for (const filename of MEADOW_ENTRY_CONTROL_FILENAMES) {
			fileSystem.writeFileSync(
				join(temporaryControls, filename),
				packageBytes.rendered[filename] ?? '',
				{ encoding: 'utf8', flag: 'wx' }
			);
		}
		fileSystem.writeFileSync(temporaryGenerated, packageBytes.generatedContents, {
			encoding: 'utf8',
			flag: 'wx'
		});

		if (hadControls) {
			fileSystem.renameSync(paths.controlsDirectory, join(backupDirectory, 'controls'));
			state.controlsBackedUp = true;
		}
		if (hadGenerated) {
			fileSystem.renameSync(paths.generatedPath, join(backupDirectory, 'generated.ts'));
			state.generatedBackedUp = true;
		}
		fileSystem.renameSync(temporaryControls, paths.controlsDirectory);
		state.controlsPublished = true;
		fileSystem.renameSync(temporaryGenerated, paths.generatedPath);
		state.generatedPublished = true;
		packagePublished = true;
		fileSystem.rmSync(backupDirectory, { recursive: true });
	} catch (error) {
		if (!packagePublished) {
			restorePreviousPackage(paths, fileSystem, backupDirectory, state);
			if (fileSystem.existsSync(backupDirectory)) {
				fileSystem.rmSync(backupDirectory, { recursive: true });
			}
		}
		throw error;
	} finally {
		if (fileSystem.existsSync(temporaryControls)) {
			fileSystem.rmSync(temporaryControls, { recursive: true });
		}
		if (fileSystem.existsSync(temporaryGeneratedDirectory)) {
			fileSystem.rmSync(temporaryGeneratedDirectory, { recursive: true });
		}
	}
}

export function runMeadowEntryArtControlsExporter(
	args: readonly string[],
	repositoryRoot = process.cwd()
): void {
	const { checkMode, packageName } = parseExportArguments(args);
	const paths = meadowEntryExportPaths(repositoryRoot, packageName);
	const { packageBytes, combinedControlFingerprint } = buildExportPackage(
		repositoryRoot,
		packageName
	);
	if (checkMode) {
		checkMeadowEntryExportPackage(packageBytes, paths);
		console.log(`${packageName} meadow-entry controls are current\t${combinedControlFingerprint}`);
	} else {
		publishMeadowEntryExportPackage(packageBytes, paths);
		console.log(
			`wrote ${MEADOW_ENTRY_CONTROL_FILENAMES.length} ${packageName} meadow-entry controls`
		);
		console.log(`combinedControlFingerprint\t${combinedControlFingerprint}`);
	}
}

if (import.meta.main) runMeadowEntryArtControlsExporter(process.argv.slice(2));
