import { randomUUID } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

import { npcDialogueList } from '../src/lib/game/content/dialogue';
import { enemies } from '../src/lib/game/content/enemies';
import { maps } from '../src/lib/game/content/maps';
import { questList } from '../src/lib/game/content/quests';
import { shopList } from '../src/lib/game/content/shops';

export interface StoryContentReferences {
	readonly mapIds: readonly string[];
	readonly npcIds: readonly string[];
	readonly questIds: readonly string[];
	readonly shopIds: readonly string[];
	readonly enemyIds: readonly string[];
	readonly npcPlacements: readonly (readonly [mapId: string, dialogueId: string])[];
}

function sortedUnique(label: string, values: readonly string[]): readonly string[] {
	const sorted = [...values].sort();
	for (let index = 1; index < sorted.length; index += 1) {
		if (sorted[index] === sorted[index - 1]) {
			throw new Error(`duplicate ${label} ${sorted[index]}`);
		}
	}
	return sorted;
}

function comparePlacements(
	[leftMapId, leftDialogueId]: readonly [string, string],
	[rightMapId, rightDialogueId]: readonly [string, string]
): number {
	if (leftMapId !== rightMapId) return leftMapId < rightMapId ? -1 : 1;
	if (leftDialogueId !== rightDialogueId) return leftDialogueId < rightDialogueId ? -1 : 1;
	return 0;
}

export function normalizeStoryContentReferences(
	input: StoryContentReferences
): StoryContentReferences {
	const npcPlacements = input.npcPlacements
		.map(([mapId, dialogueId]) => [mapId, dialogueId] as const)
		.sort(comparePlacements);
	for (let index = 1; index < npcPlacements.length; index += 1) {
		const [mapId, dialogueId] = npcPlacements[index]!;
		const [previousMapId, previousDialogueId] = npcPlacements[index - 1]!;
		if (mapId === previousMapId && dialogueId === previousDialogueId) {
			throw new Error(`duplicate npc placement ${mapId}/${dialogueId}`);
		}
	}
	const dialogueIds = npcPlacements.map(([, dialogueId]) => dialogueId).sort();
	for (let index = 1; index < dialogueIds.length; index += 1) {
		if (dialogueIds[index] === dialogueIds[index - 1]) {
			const dialogueId = dialogueIds[index]!;
			const maps = npcPlacements.filter(([, id]) => id === dialogueId).map(([mapId]) => mapId);
			throw new Error(
				`npc ${dialogueId} is placed on multiple maps (${maps.join(', ')}); the runtime model requires exactly one map per npc`
			);
		}
	}
	return {
		mapIds: sortedUnique('map id', input.mapIds),
		npcIds: sortedUnique('npc id', input.npcIds),
		questIds: sortedUnique('quest id', input.questIds),
		shopIds: sortedUnique('shop id', input.shopIds),
		enemyIds: sortedUnique('enemy id', input.enemyIds),
		npcPlacements
	};
}

export function collectStoryContentReferences(): StoryContentReferences {
	const mapList = Object.values(maps);
	return normalizeStoryContentReferences({
		mapIds: mapList.map((map) => map.id),
		npcIds: npcDialogueList.map((dialogue) => dialogue.id),
		questIds: questList.map((quest) => quest.id),
		shopIds: shopList.map((shop) => shop.id),
		enemyIds: Object.values(enemies).map((enemy) => enemy.id),
		npcPlacements: mapList.flatMap((map) =>
			(map.npcs ?? []).map((npc) => [map.id, npc.dialogueId] as const)
		)
	});
}

function rustString(value: string): string {
	return `"${value
		.replaceAll('\\', '\\\\')
		.replaceAll('"', '\\"')
		.replaceAll('\n', '\\n')
		.replaceAll('\r', '\\r')
		.replaceAll('\t', '\\t')}"`;
}

function renderIdList(name: string, ids: readonly string[]): string {
	const inline = `pub const ${name}: &[&str] = &[${ids.map(rustString).join(', ')}];`;
	if (inline.length <= 100) return inline;
	return `pub const ${name}: &[&str] = &[\n${ids.map((id) => `    ${rustString(id)},`).join('\n')}\n];`;
}

function renderNpcPlacements(placements: StoryContentReferences['npcPlacements']): string {
	return `pub const NPC_PLACEMENTS: &[(&str, &str)] = &[\n${placements
		.map(([mapId, dialogueId]) => `    (${rustString(mapId)}, ${rustString(dialogueId)}),`)
		.join('\n')}\n];`;
}

export function renderStoryContentReferences(input: StoryContentReferences): string {
	const references = normalizeStoryContentReferences(input);
	return [
		'// @generated by tools/export-story-content-references.ts. Do not edit by hand.',
		'',
		renderIdList('MAP_IDS', references.mapIds),
		'',
		renderIdList('NPC_IDS', references.npcIds),
		'',
		renderIdList('QUEST_IDS', references.questIds),
		'',
		renderIdList('SHOP_IDS', references.shopIds),
		'',
		renderIdList('ENEMY_IDS', references.enemyIds),
		'',
		renderNpcPlacements(references.npcPlacements),
		''
	].join('\n');
}

export function syncGeneratedStoryContentReferences(
	source: string,
	destinationPath: string,
	check: boolean
): void {
	if (check) {
		if (!existsSync(destinationPath)) {
			throw new Error(`generated story references are missing: ${destinationPath}`);
		}
		if (readFileSync(destinationPath, 'utf8') !== source) {
			throw new Error(`generated story references are stale: ${destinationPath}`);
		}
		return;
	}

	mkdirSync(dirname(destinationPath), { recursive: true });
	const temporaryPath = `${destinationPath}.${process.pid}.${randomUUID()}.tmp`;
	try {
		writeFileSync(temporaryPath, source, { encoding: 'utf8', flag: 'wx' });
		renameSync(temporaryPath, destinationPath);
	} finally {
		if (existsSync(temporaryPath)) rmSync(temporaryPath);
	}
}

function parseCheckMode(args: readonly string[]): boolean {
	if (args.length === 0) return false;
	if (args.length === 1 && args[0] === '--check') return true;
	throw new Error('Usage: bun tools/export-story-content-references.ts [--check]');
}

export function runStoryContentReferenceExporter(
	args: readonly string[],
	repositoryRoot = process.cwd()
): void {
	const check = parseCheckMode(args);
	const destination = resolve(repositoryRoot, 'src-tauri/src/story/reference.rs');
	const source = renderStoryContentReferences(collectStoryContentReferences());
	syncGeneratedStoryContentReferences(source, destination, check);
	console.log(check ? 'story content references are current' : 'wrote story content references');
}

if (import.meta.main) runStoryContentReferenceExporter(process.argv.slice(2));
