import {
	existsSync,
	mkdirSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	renameSync,
	rmSync,
	rmdirSync,
	writeFileSync
} from 'node:fs';
import { basename, dirname, join, relative, resolve } from 'node:path';

import {
	buildMeadowEntryControlInputs,
	computeMeadowEntryAuthoringContractFingerprint,
	computeMeadowEntryCombinedControlFingerprint,
	computeMeadowEntryGameplaySourceFingerprint,
	MEADOW_ENTRY_CONTROL_FILENAMES,
	renderMeadowEntryControls
} from '../src/lib/game/content/backgrounds/meadow-entry-controls';

const repositoryRoot = resolve(process.cwd());
const controlsDirectory = resolve(repositoryRoot, 'docs/superpowers/reports/img/hpa-399/controls');
const generatedPath = resolve(
	repositoryRoot,
	'src/lib/game/content/generated/meadow-entry-art-control.ts'
);
const allowedControlFilenames = new Set<string>(MEADOW_ENTRY_CONTROL_FILENAMES);

function parseCheckMode(args: readonly string[]): boolean {
	if (args.length === 0) return false;
	if (args.length === 1 && args[0] === '--check') return true;
	throw new Error(`Usage: bun tools/export-meadow-entry-art-controls.ts [--check]`);
}

function assertAllowedDestination(path: string): void {
	const relativePath = relative(repositoryRoot, path).replaceAll('\\', '/');
	const allowed =
		relativePath === 'src/lib/game/content/generated/meadow-entry-art-control.ts' ||
		(relativePath.startsWith('docs/superpowers/reports/img/hpa-399/controls/') &&
			allowedControlFilenames.has(
				relativePath.slice('docs/superpowers/reports/img/hpa-399/controls/'.length)
			));
	if (!allowed || relativePath.includes('/hpa-307/') || relativePath.includes('/hpa-398/')) {
		throw new Error(`Refusing unexpected meadow-entry control destination: ${relativePath}`);
	}
}

function generatedModule(
	gameplaySourceFingerprint: string,
	authoringContractFingerprint: string,
	combinedControlFingerprint: string
): string {
	return `/** @generated by tools/export-meadow-entry-art-controls.ts */
export const MEADOW_ENTRY_GAMEPLAY_SOURCE_FINGERPRINT =
\t'${gameplaySourceFingerprint}';
export const MEADOW_ENTRY_AUTHORING_CONTRACT_FINGERPRINT =
\t'${authoringContractFingerprint}';
export const MEADOW_ENTRY_COMBINED_CONTROL_FINGERPRINT =
\t'${combinedControlFingerprint}';
`;
}

function assertRenderedInventory(rendered: Readonly<Record<string, string>>): void {
	const actual = Object.keys(rendered);
	if (
		actual.length !== MEADOW_ENTRY_CONTROL_FILENAMES.length ||
		actual.some((filename, index) => filename !== MEADOW_ENTRY_CONTROL_FILENAMES[index])
	) {
		throw new Error(
			`Rendered meadow-entry control inventory drifted: ${actual.join(', ') || '(empty)'}`
		);
	}
	for (const filename of actual) {
		if (filename !== basename(filename) || filename.includes('..')) {
			throw new Error(`Refusing nested meadow-entry control path: ${filename}`);
		}
		assertAllowedDestination(join(controlsDirectory, filename));
	}
	assertAllowedDestination(generatedPath);
}

function checkedInControlFilenames(): readonly string[] {
	if (!existsSync(controlsDirectory)) return [];
	return readdirSync(controlsDirectory, { withFileTypes: true })
		.map((entry) => {
			if (!entry.isFile()) {
				throw new Error(`Unexpected non-file in meadow-entry control inventory: ${entry.name}`);
			}
			return entry.name;
		})
		.sort();
}

function assertNoUnexpectedCheckedInPaths(): void {
	const expected = [...MEADOW_ENTRY_CONTROL_FILENAMES].sort();
	const actual = checkedInControlFilenames();
	if (
		actual.length !== expected.length ||
		actual.some((filename, index) => filename !== expected[index])
	) {
		throw new Error(
			`Checked-in meadow-entry control inventory differs from the fixed allowlist: expected [${expected.join(', ')}], received [${actual.join(', ')}]`
		);
	}
}

function checkBytes(rendered: Readonly<Record<string, string>>, generatedContents: string): void {
	assertNoUnexpectedCheckedInPaths();
	for (const filename of MEADOW_ENTRY_CONTROL_FILENAMES) {
		const path = join(controlsDirectory, filename);
		assertAllowedDestination(path);
		const actual = readFileSync(path);
		const expected = Buffer.from(rendered[filename] ?? '', 'utf8');
		if (!actual.equals(expected)) {
			throw new Error(`Generated meadow-entry control is stale: ${relative(repositoryRoot, path)}`);
		}
	}
	assertAllowedDestination(generatedPath);
	if (!existsSync(generatedPath) || readFileSync(generatedPath, 'utf8') !== generatedContents) {
		throw new Error(
			`Generated meadow-entry fingerprint module is stale: ${relative(repositoryRoot, generatedPath)}`
		);
	}
}

function writeAtomically(
	rendered: Readonly<Record<string, string>>,
	generatedContents: string
): void {
	const controlsParent = dirname(controlsDirectory);
	const generatedParent = dirname(generatedPath);
	mkdirSync(controlsParent, { recursive: true });
	mkdirSync(generatedParent, { recursive: true });

	if (existsSync(controlsDirectory)) assertNoUnexpectedCheckedInPaths();
	const temporaryControls = mkdtempSync(join(controlsParent, '.meadow-entry-controls-'));
	const generatedTemporary = `${generatedPath}.tmp-${process.pid}`;
	let controlsBackup: string | null = null;
	try {
		for (const filename of MEADOW_ENTRY_CONTROL_FILENAMES) {
			writeFileSync(join(temporaryControls, filename), rendered[filename] ?? '', {
				encoding: 'utf8',
				flag: 'wx'
			});
		}
		writeFileSync(generatedTemporary, generatedContents, { encoding: 'utf8', flag: 'wx' });

		if (existsSync(controlsDirectory)) {
			controlsBackup = mkdtempSync(join(controlsParent, '.meadow-entry-controls-backup-'));
			rmdirSync(controlsBackup);
			renameSync(controlsDirectory, controlsBackup);
		}
		renameSync(temporaryControls, controlsDirectory);
		renameSync(generatedTemporary, generatedPath);
		if (controlsBackup) rmSync(controlsBackup, { recursive: true });
	} catch (error) {
		if (controlsBackup && existsSync(controlsBackup)) {
			if (existsSync(controlsDirectory)) rmSync(controlsDirectory, { recursive: true });
			renameSync(controlsBackup, controlsDirectory);
		}
		throw error;
	} finally {
		if (existsSync(temporaryControls)) rmSync(temporaryControls, { recursive: true });
		if (existsSync(generatedTemporary)) rmSync(generatedTemporary);
	}
}

const checkMode = parseCheckMode(process.argv.slice(2));
const inputs = buildMeadowEntryControlInputs();
const rendered = renderMeadowEntryControls(inputs);
assertRenderedInventory(rendered);
const gameplaySourceFingerprint = computeMeadowEntryGameplaySourceFingerprint(inputs);
const authoringContractFingerprint = computeMeadowEntryAuthoringContractFingerprint(inputs);
const combinedControlFingerprint = computeMeadowEntryCombinedControlFingerprint(inputs);
const generatedContents = generatedModule(
	gameplaySourceFingerprint,
	authoringContractFingerprint,
	combinedControlFingerprint
);

if (checkMode) {
	checkBytes(rendered, generatedContents);
	console.log(`meadow-entry controls are current\t${combinedControlFingerprint}`);
} else {
	writeAtomically(rendered, generatedContents);
	console.log(`wrote ${MEADOW_ENTRY_CONTROL_FILENAMES.length} meadow-entry controls`);
	console.log(`combinedControlFingerprint\t${combinedControlFingerprint}`);
}
