import { mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

import { buildVillageArtControlInputs } from '$lib/game/content/maps/layered/village-art-control-inputs';
import {
	VILLAGE_ART_CONTROL_FILENAMES,
	computeVillageArtControlFingerprint,
	renderVillageArtControlArtifacts
} from '$lib/game/content/maps/layered/village-art-controls';
import { sundropVillageLayered } from '$lib/game/content/maps/regions/village-layered';

const repositoryRoot = process.cwd();
const outputDirectory = join(repositoryRoot, 'docs/superpowers/reports/img/hpa-307');
const generatedFile = join(
	repositoryRoot,
	'src/lib/game/content/generated/sundrop-village-art-control.ts'
);

function assertAllowedOutputPath(path: string): void {
	const repositoryPath = relative(repositoryRoot, path).split(sep).join('/');
	if (repositoryPath.includes('/img/hpa-238/')) {
		throw new Error(`refusing to write historical HPA-238 output: ${repositoryPath}`);
	}
	if (repositoryPath.endsWith('/village-composed-collision.svg')) {
		throw new Error(`refusing to write legacy collision filename: ${repositoryPath}`);
	}

	const allowed = new Set([
		...VILLAGE_ART_CONTROL_FILENAMES.map((name) => `docs/superpowers/reports/img/hpa-307/${name}`),
		'src/lib/game/content/generated/sundrop-village-art-control.ts'
	]);
	if (!allowed.has(repositoryPath)) {
		throw new Error(`refusing output outside fixed HPA-307 inventory: ${repositoryPath}`);
	}
}

function normalizeText(content: string): string {
	return `${content.replaceAll('\r\n', '\n').replace(/\n*$/, '')}\n`;
}

const inputs = buildVillageArtControlInputs();
const fingerprint = computeVillageArtControlFingerprint(sundropVillageLayered, inputs);
const artifacts = renderVillageArtControlArtifacts(sundropVillageLayered, inputs);
const generatedContent = normalizeText(`/** @generated by tools/export-village-art-controls.ts */
export const SUNDROP_VILLAGE_ART_CONTROL_FINGERPRINT =
\t'${fingerprint}';
`);
const outputs = new Map<string, string>(
	[...artifacts].map(([filename, content]) => [
		join(outputDirectory, filename),
		normalizeText(content)
	])
);
outputs.set(generatedFile, generatedContent);

mkdirSync(outputDirectory, { recursive: true });
mkdirSync(join(repositoryRoot, 'src/lib/game/content/generated'), { recursive: true });

const sortedOutputs = [...outputs].sort(([a], [b]) => a.localeCompare(b));
for (const [path] of sortedOutputs) {
	assertAllowedOutputPath(path);
}
for (const [path, content] of sortedOutputs) {
	writeFileSync(path, content, { encoding: 'utf8' });
	const repositoryPath = relative(repositoryRoot, path).split(sep).join('/');
	console.log(`${repositoryPath}\t${Buffer.byteLength(content, 'utf8')} bytes`);
}
console.log(`fingerprint\t${fingerprint}`);
