import { mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

import {
	buildSundropVillageObstacleControlInputs,
	computeSundropVillageObstacleControlFingerprint,
	renderSundropVillageObstacleControlArtifacts,
	SUNDROP_VILLAGE_OBSTACLE_CONTROL_FILENAMES
} from '$lib/game/content/backgrounds/sundrop-village-obstacle-controls';

const repositoryRoot = process.cwd();
const outputDirectory = join(repositoryRoot, 'docs/superpowers/reports/img/hpa-398');
const generatedFile = join(
	repositoryRoot,
	'src/lib/game/content/generated/sundrop-village-obstacle-control.ts'
);

function normalizeText(content: string): string {
	return `${content.replaceAll('\r\n', '\n').replace(/\n*$/, '')}\n`;
}

function assertAllowedOutputPath(path: string): void {
	const repositoryPath = relative(repositoryRoot, path).split(sep).join('/');
	const allowed = new Set([
		...SUNDROP_VILLAGE_OBSTACLE_CONTROL_FILENAMES.map(
			(filename) => `docs/superpowers/reports/img/hpa-398/${filename}`
		),
		'src/lib/game/content/generated/sundrop-village-obstacle-control.ts'
	]);
	if (!allowed.has(repositoryPath)) {
		throw new Error(`refusing output outside fixed HPA-398 inventory: ${repositoryPath}`);
	}
}

const inputs = buildSundropVillageObstacleControlInputs(repositoryRoot);
const artifacts = renderSundropVillageObstacleControlArtifacts(inputs);
const fingerprint = computeSundropVillageObstacleControlFingerprint(inputs);
const outputs = new Map<string, string>(
	[...artifacts].map(([filename, content]) => [
		join(outputDirectory, filename),
		normalizeText(content)
	])
);
outputs.set(
	generatedFile,
	normalizeText(`/** @generated by tools/export-sundrop-village-obstacle-controls.ts */
export const SUNDROP_VILLAGE_OBSTACLE_CONTROL_FINGERPRINT =
	'${fingerprint}';`)
);

mkdirSync(outputDirectory, { recursive: true });
mkdirSync(join(repositoryRoot, 'src/lib/game/content/generated'), { recursive: true });
for (const [path] of [...outputs].sort(([left], [right]) => left.localeCompare(right))) {
	assertAllowedOutputPath(path);
}
for (const [path, content] of [...outputs].sort(([left], [right]) => left.localeCompare(right))) {
	writeFileSync(path, content, { encoding: 'utf8' });
	console.log(`${relative(repositoryRoot, path)}\t${Buffer.byteLength(content, 'utf8')} bytes`);
}
console.log(`fingerprint\t${fingerprint}`);
