import { randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';

import {
	compileNavigationGrid,
	type NavigationGrid,
	type NavigationMaskSource
} from '$lib/game/core/navigation';
import { NAVIGATION_MASK_SOURCES } from '$lib/game/content/backgrounds/navigation-source-registry';

export const NAVIGATION_RUNTIME_RELATIVE_PATH =
	'src/lib/game/content/generated/navigation-grids.generated.ts';

function assert(condition: unknown, message: string): asserts condition {
	if (!condition) throw new Error(message);
}

function compareSources(left: NavigationMaskSource, right: NavigationMaskSource): number {
	return left.id < right.id ? -1 : left.id > right.id ? 1 : left.mapId < right.mapId ? -1 : 1;
}

export function validateNavigationSources(
	sources: readonly NavigationMaskSource[]
): readonly NavigationMaskSource[] {
	const sourceIds = new Set<string>();
	const mapIds = new Set<string>();
	for (const source of sources) {
		assert(source.id.length > 0, 'Navigation source ID is required');
		assert(source.mapId.length > 0, 'Navigation source map ID is required');
		assert(!sourceIds.has(source.id), `Navigation source ID is duplicated: ${source.id}`);
		assert(!mapIds.has(source.mapId), `Navigation source map ID is duplicated: ${source.mapId}`);
		sourceIds.add(source.id);
		mapIds.add(source.mapId);
		compileNavigationGrid(source);
	}
	return [...sources].sort(compareSources);
}

function renderGrid(grid: NavigationGrid): string {
	return [
		`\t${JSON.stringify(grid.id)}: {`,
		`\t\tid: ${JSON.stringify(grid.id)},`,
		`\t\tmapId: ${JSON.stringify(grid.mapId)},`,
		`\t\tcellSizePx: ${grid.cellSizePx},`,
		`\t\twidthCells: ${grid.widthCells},`,
		`\t\theightCells: ${grid.heightCells},`,
		`\t\twidthPx: ${grid.widthPx},`,
		`\t\theightPx: ${grid.heightPx},`,
		`\t\tblockedBits: new Uint8Array([${[...grid.blockedBits].join(', ')}])`,
		'\t}'
	].join('\n');
}

export function renderNavigationRuntime(sources: readonly NavigationMaskSource[]): string {
	const grids = validateNavigationSources(sources).map((source) => compileNavigationGrid(source));
	const entries = grids.map(renderGrid).join(',\n');
	const registry = entries
		? [
				'export const GENERATED_NAVIGATION_GRIDS = Object.freeze({',
				entries,
				'}) satisfies Readonly<Record<string, NavigationGrid>>;'
			]
		: [
				'export const GENERATED_NAVIGATION_GRIDS = Object.freeze({}) satisfies Readonly<Record<string, NavigationGrid>>;'
			];
	return [
		'// @generated by tools/generate-navigation-runtime.ts. Do not edit by hand.',
		'',
		"import type { NavigationGrid } from '$lib/game/core/navigation';",
		'',
		...registry,
		''
	].join('\n');
}

export function parseNavigationRuntimeArguments(args: readonly string[]): {
	readonly check: boolean;
} {
	let check = false;
	for (const argument of args) {
		if (argument === '--check' && !check) {
			check = true;
			continue;
		}
		throw new Error('Usage: bun tools/generate-navigation-runtime.ts [--check]');
	}
	return { check };
}

function assertCanonicalDestination(destinationPath: string, repositoryRoot: string): string {
	const canonical = resolve(repositoryRoot, NAVIGATION_RUNTIME_RELATIVE_PATH);
	const destination = resolve(destinationPath);
	assert(
		relative(canonical, destination) === '',
		`Navigation runtime destination must be canonical: ${destination}`
	);
	return canonical;
}

export async function syncGeneratedNavigationRuntime(
	source: string,
	destinationPath: string,
	check: boolean,
	repositoryRoot = process.cwd()
): Promise<void> {
	const destination = assertCanonicalDestination(destinationPath, repositoryRoot);
	if (check) {
		let existing: Buffer;
		try {
			existing = await readFile(destination);
		} catch (error) {
			throw new Error(`generated navigation runtime is missing: ${destination}`, { cause: error });
		}
		assert(
			existing.equals(Buffer.from(source, 'utf8')),
			`generated navigation runtime is stale: ${destination}`
		);
		return;
	}

	await mkdir(dirname(destination), { recursive: true });
	const temporary = `${destination}.${process.pid}.${randomUUID()}.tmp`;
	try {
		await writeFile(temporary, source, { encoding: 'utf8', flag: 'wx' });
		await rename(temporary, destination);
	} finally {
		await rm(temporary, { force: true });
	}
}

export async function runNavigationRuntimeGenerator(
	args: readonly string[],
	repositoryRoot = process.cwd()
): Promise<void> {
	const { check } = parseNavigationRuntimeArguments(args);
	const source = renderNavigationRuntime(NAVIGATION_MASK_SOURCES);
	const destination = resolve(repositoryRoot, NAVIGATION_RUNTIME_RELATIVE_PATH);
	await syncGeneratedNavigationRuntime(source, destination, check, repositoryRoot);
	console.log(check ? 'navigation runtime is current' : 'wrote navigation runtime');
}

if (import.meta.main) {
	await runNavigationRuntimeGenerator(process.argv.slice(2));
}
