import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import type { NavigationMaskSource } from '$lib/game/core/navigation';
import {
	MEADOW_ENTRY_NAVIGATION_SOURCES,
	NAVIGATION_MASK_SOURCES
} from '$lib/game/content/backgrounds/navigation-source-registry';
import { VILLAGE_INTERIOR_NAVIGATION_SOURCES } from '$lib/game/content/backgrounds/village-interior-navigation-sources';
import {
	parseNavigationRuntimeArguments,
	renderNavigationRuntime,
	syncGeneratedNavigationRuntime,
	validateNavigationSources
} from './generate-navigation-runtime';

const temporaryRoots: string[] = [];

afterEach(async () => {
	await Promise.all(
		temporaryRoots.splice(0).map((root) => rm(root, { recursive: true, force: true }))
	);
});

function source(overrides: Partial<NavigationMaskSource> = {}): NavigationMaskSource {
	return {
		id: 'tiny-grid',
		mapId: 'tiny-map',
		cellSizePx: 16,
		widthCells: 3,
		heightCells: 2,
		clearancePx: 0,
		rows: ['.#.', '...'],
		...overrides
	};
}

describe('navigation runtime generator', () => {
	it('aggregates the Meadow and interior source registries through one frozen input', () => {
		expect(NAVIGATION_MASK_SOURCES).toEqual([
			...MEADOW_ENTRY_NAVIGATION_SOURCES,
			...VILLAGE_INTERIOR_NAVIGATION_SOURCES
		]);
		expect(Object.isFrozen(NAVIGATION_MASK_SOURCES)).toBe(true);
	});

	it('sorts sources deterministically and emits packed compiled bytes without glyph rows', () => {
		const rendered = renderNavigationRuntime([
			source({ id: 'z-grid', mapId: 'z-map' }),
			source({ id: 'a-grid', mapId: 'a-map' })
		]);

		expect(rendered.indexOf('a-grid')).toBeLessThan(rendered.indexOf('z-grid'));
		expect(rendered).toContain('blockedBits: new Uint8Array([2])');
		expect(rendered).not.toContain("rows: ['.#.', '...']");
		expect(rendered).toContain('// @generated by tools/generate-navigation-runtime.ts');
	});

	it('rejects duplicate source IDs, map IDs, and invalid masks', () => {
		expect(() => validateNavigationSources([source(), source()])).toThrow(/source ID/i);
		expect(() =>
			validateNavigationSources([source(), source({ id: 'other-grid', mapId: 'tiny-map' })])
		).toThrow(/map ID/i);
		expect(() => validateNavigationSources([source({ rows: ['..x', '...'] })])).toThrow(
			/glyph|navigation/i
		);
	});

	it('parses check mode and rejects unknown or repeated flags', () => {
		expect(parseNavigationRuntimeArguments([])).toEqual({ check: false });
		expect(parseNavigationRuntimeArguments(['--check'])).toEqual({ check: true });
		expect(() => parseNavigationRuntimeArguments(['--check', '--check'])).toThrow(/Usage/);
		expect(() => parseNavigationRuntimeArguments(['--other'])).toThrow(/Usage/);
	});

	it('atomically writes and checks only the canonical generated destination', async () => {
		const root = await mkdtemp(join(tmpdir(), 'gliese-navigation-generator-'));
		temporaryRoots.push(root);
		const destination = resolve(
			root,
			'src/lib/game/content/generated/navigation-grids.generated.ts'
		);
		const rendered = renderNavigationRuntime([]);

		await syncGeneratedNavigationRuntime(rendered, destination, false, root);
		expect(await readFile(destination, 'utf8')).toBe(rendered);
		await expect(
			syncGeneratedNavigationRuntime(rendered, destination, true, root)
		).resolves.toBeUndefined();
		await expect(
			syncGeneratedNavigationRuntime(rendered, join(root, 'other.ts'), false, root)
		).rejects.toThrow(/canonical/i);
		await writeFile(
			destination,
			rendered.replace('Object.freeze({', 'Object.freeze({ stale: true,')
		);
		await expect(syncGeneratedNavigationRuntime(rendered, destination, true, root)).rejects.toThrow(
			/stale/i
		);
	});
});
